application: dofriends
version: 1
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bat)|
 (.*\.txt)|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$

default_expiration: '3650d'

handlers:
- url: /media
  static_dir: _generated_media
  secure: optional

- url: /media/.*
  script: secureZipServe.py
  
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico
  mime_type: image/x-icon 

- url: /js/.*
  script: secureZipServe.py

- url: /static/.*
  script: secureZipServe.py
  
- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
