#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACehJ"
    "REFUWIWNl3lwVdUdxz/n3ndf8l7yXl7CEhK2LEAIARpBU01ICy6gQ0VbLFodxWKhtrhUS63i"
    "jLXLiFW7qVO0YotMEYZxGWWRFqJUpSC1skgRCEQSkkBCtpe33nfvOad/3NCUotjfzJlz586Z"
    "8/vc7+93fvf8hPaML7Kza6RUdJ6OorQCpYlF4/xw6Sp6OmMYGpRSDCmK8OKGZRSOyEMIccF9"
    "xYUAenvitLZ0IQzBpk17OdnSg7ZdGnYdRVp+ZF4usiAPOzcHJzeAzMlBa43/cBNDGxtZ8+d7"
    "qbls/P8PoLXGcSS7dx7m3YaD/OOfTWzdtpcxwRwuKwlSXSCZkCtZ/41FvFxYDgEfuC44ChyJ"
    "cEFIhWH5MNduYoERY9XLP8CyzC8GsG2H55/9C+tXv8+oEBRlOVQX+aku1Aw3UkRkimw7jkjE"
    "OFRVz9UXL6QjLZkUNCgP+CjONhkTMCnLMRkV8PHrPe1svvNXrFh6Jfc8cP2FAZRS3L/0Bf7+"
    "1se8sLic8UNdsrUNyRQynoR4GlwHevoQySSG6/Dzmx5mRaiC3bUFTA5Z2FLTmpLk+Ax6M5JP"
    "YpLbn3mXys1beeWNBykpL/x8gCOftDL7ykd4cWEFs8a6KEeibQfSNqJ0PMaEKaAk2Bn037Yj"
    "drzNp+OmMGfucuaXRSgJmLzVmiSmNCUBHxq4OGKxqjHOkcdW851JBTzxu0UEgv7zAAyAjW9+"
    "yKgsQU1pNjKWRqfSkEpjFI/GnHcT9HTB0SPodxsw5n8Lausp2bebBZ2HeOOMi98QVIQtfjIp"
    "QsQveLQqj56MZMmEMFxVx4tr/8rxxlN8VrIbWmv+9XELS68oJJjpB9OEZAqRSiMqpqC2b0H9"
    "fQfiokvg2FHUM08h5s1HBHL4/tbVuIkkWaYgoTT9jiLlapTWZBsGZUGTqdPL8F80nXV/akCr"
    "zwA4faqXE/ubuKrUhFgSgUCkUpBOgeGD9lY4ehg62jF+8jhcWg8dHYjxlYx6bxt3HPuAta1p"
    "Lor4+fGBXrozisV7utnWnqI54XJrRYTU7K/wxpYDRKPJ8wDMrlPFj44kxg1VJqo/gfD7IRrz"
    "VMjNRUycDLveRx86iN61E3ZsR8yaDXs+QBw4SGGsl2cmXcXc0TnMHh5gctjionw/Y3J8tKYk"
    "29sSNPlD2IeOk93ZRf2syecA+PZ9dILv14ahtxekRPf1DYQhiX5vB8aUaTBzNnrT65BMYtTU"
    "IUJh9M5d4EpK9+7hmq5GHjkUYLRfcCjqcKrfAakxpMKHIigU5iUVrH25gRtu+QrjK4oHASzL"
    "pDfueunoSnBthD8Lkinoi6Ke+Bli/s0YP33CA+vqQi9/ADo6IONiOb0s3ryadQt/SXtLJ0X2"
    "Geb4TlISbGJsVhtFVhtDdQfhmSkebBjP66/uYdmD12EYXokWez9q0ivufJq183zorh5QCqws"
    "RMtJT5VMBmG7EAiA4yCa2+BMN442iIZDNI8awQdTKzCuKad66HuMyz9CntGL3xTgs0DYoAWg"
    "eW1LGSs33sxrbz5EKBzwFCgqyudk0uBQt0kVGuW44CooKIDWNkQ6A3YG0XYKmc7QFx7Kh7On"
    "8l51CTvLgxwZIoiKNPcN72FJeB+mTIEGzFIYdh+03Q0F34H+zVw5o4XfvnSQaDQ5CFA4IkLN"
    "rImsPnCYFZUKQ7rgSHSWH0NqRG8/aSE4NqGChsumsHHyEA4W2Jwx45CJgdKgFBv7s7k3VMhw"
    "TkFwBmSawQjDiMchUA19bxGOGMyp/ZSnHtvEb1cu9AAArpt3KQv+0MD3SkKUyATCdcHJoPIi"
    "HMkbxpqvz+DVcSbtZh9ppwOkC87AmdYAiqakzX5Zw1XiDbDGQGgehL7mQagYDFsKGMyse5ob"
    "797B7Yu/SvW0Eq8S1tZPpO6KarafkPgcG1wXZWdYf3k9Nz84l19NjNGkWsnYcWZEynm47FoW"
    "j5lJsRUC5YJWJN0M6/sKUWYexBpAJTznwgQzAv5K6HyeaeM7GDOsmYP7Tw6WYr/fR83FZWxq"
    "9aGyszDSaZpD+fyi3MfHyRZUJg5Kc/mQCv5UdTsZaTM1t5iXp32PAisIWoGW/DUqaVETYch3"
    "we0F9/R//XWA8BwCfsF9dzSzdeuHgwAA9z90PZ1GkL/15CKk4p3SYppl98CfEISU1OWXs73r"
    "XzzZ+CbLDrxEl93PrSNrvZBoTVuym3dSI9GnHoXuP0J0I3Q9B4n34dTjIBOgBdfUnqT9+F72"
    "7/10EMCyTOqvnMrKRj9JK8i2ESFsNwV2BmyBRtKa6qEqVEzIzEJqSb+borZgAmMDw0BnQKXZ"
    "Fg1imwEwgpA5Aa33Q+JDUBnoWgMyQ06+S3nRcVpbes69ER080MysGQ+z6mqL5d8s4ZNks5dl"
    "lgW5LkP8flZOvYOMdujJxKmJlDMykI8pBGub3+cXhzYw2oK3S3cx1GkCNfB12gKtB/IFMGHD"
    "lvEse2bOoAIAFZWjuO22y3m+N0iLLzYQWw0ZB9LQbSe446OVrGvZyf6+Zm7c9RRL/vk8TYlO"
    "FpXMojArTFvaptkZLLVoQDme87MWtwjEFB090fMvpR/vO8GCW39D4z0C5evxNtAafAaEJAgJ"
    "WnoXFGGAcohYuVSHR7Or+yiOVKwsC7DYvx7kf0OAtk1Ut4UZc1m+bhrh2ofOVQCgsmo0V0yb"
    "SPbmjFf7tfaGKyHlnXkvqw3vPQZ9mTg7Og9iuw5KuuyMZw/mtwad8iPbA8jjfujW9McDbDlQ"
    "TE1NyfkAPsvk2hu+TPauBGaP3/ta7VU7UgocvNCogaHPBtqr9yjN4b4kKpWL6gkgW3KQzT50"
    "r0BoxZmYnyUvTWHmdV+jfmbV+QAAdbMmcWllKYF/+MAyB/TTIBUkBvQUypuVhrSEuANdaWhO"
    "0L73GKpZozt86DjggGk6NLblsOiFLxPNmc23bqnD8vu8Uvy/lpubzY8emc/+e39Pqi6ItKKe"
    "I4CUhERqoBdQ4Az0BbbjPUuF8NngeqBCK07H/KzfWcqGfdOpnVPPk7++HZ/P6xU+EwBges04"
    "JoTySb/TT/dsMSC1hnjSG2cVORsOOTiPzc5gComS8Oru0azYWEF3uohXNi5j2iVlmOag8J/b"
    "mmmtWbPqbe768YtkHrBwwglIpaE3OpAT2jsJ/8kFCVohbMEPwkkqOrLZsHskUTGBudfX8e0l"
    "Mxkzdth5veIFe0MpFXcteo51bbvpvzEGp7shmfEcoj2nhgLXwtftw+rNIetoHonjiksmV/Kl"
    "6jGs+M1CQqHsz21SLwgA8OnxTu5c9CwfRI+hy9JoHDBApA2MfhMjamJGfQwN5DO9ahzDiyLM"
    "vfZiKiePoqi44HP3PQfgixYl4mm2bvqI5XetQUn1H3UW3DaDG26pQwuI5Oecc9n8f+3fSGAI"
    "brf72p4AAAAASUVORK5CYII=")
geticon2Data = icon2.GetData
geticon2Image = icon2.GetImage
geticon2Bitmap = icon2.GetBitmap

