# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/
from sqlalchemy import *
from sqlalchemy.databases.mysql import *
metadata = MetaData()
gps_1m =  Table('gps_1m', metadata,
                Column(u'id', Integer(), primary_key=True, nullable=False),
                Column(u'heat_lat', Float(precision=None, asdecimal=False), primary_key=False),
                Column(u'heat_lng', Float(precision=None, asdecimal=False), primary_key=False),
                Column(u'heat_x', Integer(), primary_key=False),
                Column(u'heat_y', Integer(), primary_key=False),
                Column(u'heat_gps', String(length=128, convert_unicode=False, assert_unicode=None), primary_key=False),
                Column(u'heat_num', Integer(), primary_key=False),
                Column(u'num_connections', Integer(), primary_key=False),
                Column(u'num_failures', Integer(), primary_key=False),


                )
sample-data =  Table('sample-data', metadata,
                     Column(u'id', Integer(), primary_key=True, nullable=False),
                     Column(u'heat_lat', Integer(), primary_key=False, nullable=False),
                     Column(u'heat_lng', Integer(), primary_key=False, nullable=False),
                     Column(u'heat_x', Integer(), primary_key=False, nullable=False),
                     Column(u'heat_y', Integer(), primary_key=False, nullable=False),
                     Column(u'heat_num', Integer(), primary_key=False, nullable=False),
                     Column(u'num_connections', Integer(), primary_key=False, nullable=False),
                     Column(u'num_failures', Integer(), primary_key=False, nullable=False),


                     )