# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/
from sqlalchemy import *
from sqlalchemy.databases.mysql import *
metadata = MetaData()
smithmicro_sampleheatmapdata =  Table('smithmicro_sampleheatmapdata', metadata,
    Column(u'id', String(length=36, convert_unicode=False, assert_unicode=None), primary_key=True, nullable=False),
            Column(u'heat_gps', String(length=128, convert_unicode=False, assert_unicode=None), primary_key=False, nullable=False),
            Column(u'heat_lat', Integer(), primary_key=False, nullable=False),
            Column(u'heat_lng', Integer(), primary_key=False, nullable=False),
            Column(u'heat_x', Integer(), primary_key=False, nullable=False),
            Column(u'heat_y', Integer(), primary_key=False, nullable=False),
            Column(u'heat_num', Integer(), primary_key=False, nullable=False),
            Column(u'data_name', String(length=50, convert_unicode=False, assert_unicode=None), primary_key=False, nullable=False),
            Column(u'data_value', Integer(), primary_key=False, nullable=False),
            Column(u'timestamp', DateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )
users_geolocation =  Table('users_geolocation', metadata,
    Column(u'id', Integer(), primary_key=True, nullable=False),
            Column(u'gps', String(length=32, convert_unicode=False, assert_unicode=None), primary_key=False, nullable=False),
            Column(u'altitude', Float(precision=None, asdecimal=True), primary_key=False, nullable=False),
            Column(u'heading', Float(precision=None, asdecimal=True), primary_key=False, nullable=False),
            Column(u'horizontalAccuracy', Float(precision=None, asdecimal=True), primary_key=False, nullable=False),
            Column(u'speed', Float(precision=None, asdecimal=True), primary_key=False, nullable=False),
            Column(u'_type', String(length=32, convert_unicode=False, assert_unicode=None), primary_key=False, nullable=False),
            Column(u'verticalAccuracy', Float(precision=None, asdecimal=True), primary_key=False, nullable=False),
            Column(u'timestamp', DateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )
