# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/
from sqlalchemy import *
from sqlalchemy.databases.mysql import *
metadata = MetaData()
ps_aux =  Table('ps_aux', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'srcid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'dt_event', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'USER', MSString(length=32), primary_key=False, nullable=False),
            Column(u'PID', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'CPU', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
            Column(u'MEM', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
            Column(u'VSZ', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'RSS', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'TTY', MSString(length=16), primary_key=False, nullable=False),
            Column(u'STAT', MSString(length=16), primary_key=False, nullable=False),
            Column(u'START_TIME', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'COMMAND', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'FK_source', ps_aux.c.srcid, unique=False)
ps_source =  Table('ps_source', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'fpath', MSText(), primary_key=False, nullable=False),
    
    
    )
