# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


country =  Table('country', metadata,
    Column(u'iso', MSChar(length=2), primary_key=True, nullable=False),
            Column(u'name', MSString(length=80), primary_key=False, nullable=False),
            Column(u'printable_name', MSString(length=80), primary_key=False, nullable=False),
            Column(u'iso3', MSChar(length=3), primary_key=False),
            Column(u'numcode', MSSmallInteger(display_width=6), primary_key=False),
    
    
    )


states =  Table('states', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSChar(length=40), primary_key=False, nullable=False),
            Column(u'abbrev', MSChar(length=2), primary_key=False, nullable=False),
    
    
    )

