# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrctopMenu(wx.MenuBar):
    def __init__(self):
        pre = get_resources().LoadMenuBar("topMenu")
        self.PostCreate(pre)
        
        # Define variables for the menu items





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    menu_test_xrc = '''\
<?xml version="1.0" ?>
<resource>
  <object class="wxMenuBar" name="topMenu">
    <object class="wxMenu" name="Register">
      <label>Register</label>
      <object class="wxMenuItem" name="register_now_item">
        <label>Register Now</label>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/menu_test/menu_test_xrc', menu_test_xrc)
    __res.Load('memory:XRC/menu_test/menu_test_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Register")
    _("Register Now")

