# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


jos_alphacontent_rating =  Table('jos_alphacontent_rating', metadata,
    Column(u'ref', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'total_votes', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'total_value', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'used_ips', MSLongText(), primary_key=False, nullable=False),
            Column(u'component', MSString(length=30), primary_key=False, nullable=False),
            Column(u'cid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rid', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_attachments =  Table('jos_attachments', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'filename', MSString(length=80), primary_key=False, nullable=False),
            Column(u'filename_sys', MSString(length=255), primary_key=False, nullable=False),
            Column(u'file_type', MSString(length=30), primary_key=False, nullable=False),
            Column(u'file_size', MSInteger(display_width=6), primary_key=False, nullable=False),
            Column(u'icon_filename', MSString(length=20), primary_key=False, nullable=False),
            Column(u'display_filename', MSString(length=80), primary_key=False, nullable=False),
            Column(u'description', MSString(length=255), primary_key=False, nullable=False),
            Column(u'url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'uploader_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'article_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
    
    
    )


jos_banner =  Table('jos_banner', metadata,
    Column(u'bid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'cid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'type', MSString(length=30), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'imptotal', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'impmade', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'clicks', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'imageurl', MSString(length=100), primary_key=False, nullable=False),
            Column(u'clickurl', MSString(length=200), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False),
            Column(u'showBanner', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'editor', MSString(length=50), primary_key=False),
            Column(u'custombannercode', MSText(), primary_key=False),
            Column(u'catid', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'sticky', MSBoolean(), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'publish_up', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'publish_down', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'tags', MSText(), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'viewbanner', jos_banner.c.showBanner, unique=False)
Index(u'idx_banner_catid', jos_banner.c.catid, unique=False)

jos_bannerclient =  Table('jos_bannerclient', metadata,
    Column(u'cid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'contact', MSString(length=255), primary_key=False, nullable=False),
            Column(u'email', MSString(length=255), primary_key=False, nullable=False),
            Column(u'extrainfo', MSText(), primary_key=False, nullable=False),
            Column(u'checked_out', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSTime(timezone=False), primary_key=False),
            Column(u'editor', MSString(length=50), primary_key=False),
    
    
    )


jos_bannertrack =  Table('jos_bannertrack', metadata,
    Column(u'track_date', MSDate(), primary_key=False, nullable=False),
            Column(u'track_type', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'banner_id', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )


jos_blastchatc =  Table('jos_blastchatc', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'url', MSString(length=100), primary_key=False),
            Column(u'version', MSString(length=20), primary_key=False, nullable=False),
            Column(u'intra_id', MSString(length=100), primary_key=False),
            Column(u'priv_key', MSString(length=100), primary_key=False),
            Column(u'detached', MSBinary(length=1), primary_key=False, nullable=False),
            Column(u'adm_expand', MSBinary(length=1), primary_key=False, nullable=False),
            Column(u'width', MSString(length=6), primary_key=False, nullable=False),
            Column(u'height', MSString(length=6), primary_key=False, nullable=False),
            Column(u'd_width', MSString(length=6), primary_key=False, nullable=False),
            Column(u'd_height', MSString(length=6), primary_key=False, nullable=False),
            Column(u'frame_border', MSBinary(length=1), primary_key=False, nullable=False),
            Column(u'm_width', MSString(length=6), primary_key=False, nullable=False),
            Column(u'm_height', MSString(length=6), primary_key=False, nullable=False),
            Column(u'global_count', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'global_update', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'url', jos_blastchatc.c.url, unique=True)

jos_blastchatc_users =  Table('jos_blastchatc_users', metadata,
    Column(u'userid', MSInteger(display_width=11), primary_key=False),
            Column(u'serverid', MSInteger(display_width=11), primary_key=False),
            Column(u'sec_code', MSString(length=100), primary_key=False),
            Column(u'session_id', MSString(length=200), primary_key=True, nullable=False),
            Column(u'logged', MSBinary(length=1), primary_key=False, nullable=False),
            Column(u'last_entry', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'last_update', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'idle', MSString(length=5), primary_key=False),
            Column(u'roomid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'room_serverid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'roomname', MSString(length=100), primary_key=False),
    
    
    )
Index(u'sec_code', jos_blastchatc_users.c.sec_code, unique=True)
Index(u'userid_logged_last_update', jos_blastchatc_users.c.userid, jos_blastchatc_users.c.logged, jos_blastchatc_users.c.last_update, jos_blastchatc_users.c.session_id, unique=False)
Index(u'serverid', jos_blastchatc_users.c.serverid, jos_blastchatc_users.c.userid, jos_blastchatc_users.c.sec_code, unique=False)

jos_categories =  Table('jos_categories', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'image', MSString(length=255), primary_key=False, nullable=False),
            Column(u'section', MSString(length=50), primary_key=False, nullable=False),
            Column(u'image_position', MSString(length=30), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'editor', MSString(length=50), primary_key=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'count', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'cat_idx', jos_categories.c.section, jos_categories.c.published, jos_categories.c.access, unique=False)
Index(u'idx_access', jos_categories.c.access, unique=False)
Index(u'idx_checkout', jos_categories.c.checked_out, unique=False)


jos_components =  Table('jos_components', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=50), primary_key=False, nullable=False),
            Column(u'link', MSString(length=255), primary_key=False, nullable=False),
            Column(u'menuid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'parent', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'admin_menu_link', MSString(length=255), primary_key=False, nullable=False),
            Column(u'admin_menu_alt', MSString(length=255), primary_key=False, nullable=False),
            Column(u'option', MSString(length=50), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'admin_menu_img', MSString(length=255), primary_key=False, nullable=False),
            Column(u'iscore', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'enabled', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )
Index(u'parent_option', jos_components.c.parent, jos_components.c.option, unique=False)


jos_contact_details =  Table('jos_contact_details', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'con_position', MSString(length=255), primary_key=False),
            Column(u'address', MSText(), primary_key=False),
            Column(u'suburb', MSString(length=100), primary_key=False),
            Column(u'state', MSString(length=100), primary_key=False),
            Column(u'country', MSString(length=100), primary_key=False),
            Column(u'postcode', MSString(length=100), primary_key=False),
            Column(u'telephone', MSString(length=255), primary_key=False),
            Column(u'fax', MSString(length=255), primary_key=False),
            Column(u'misc', MSMediumText(), primary_key=False),
            Column(u'image', MSString(length=255), primary_key=False),
            Column(u'imagepos', MSString(length=20), primary_key=False),
            Column(u'email_to', MSString(length=255), primary_key=False),
            Column(u'default_con', MSBoolean(), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'user_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'mobile', MSString(length=255), primary_key=False, nullable=False),
            Column(u'webpage', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'catid', jos_contact_details.c.catid, unique=False)


jos_content =  Table('jos_content', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'title_alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'introtext', MSMediumText(), primary_key=False, nullable=False),
            Column(u'fulltext', MSMediumText(), primary_key=False, nullable=False),
            Column(u'state', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'sectionid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'mask', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'created', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'created_by', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'created_by_alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'modified', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'modified_by', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'publish_up', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'publish_down', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'images', MSText(), primary_key=False, nullable=False),
            Column(u'urls', MSText(), primary_key=False, nullable=False),
            Column(u'attribs', MSText(), primary_key=False, nullable=False),
            Column(u'version', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'parentid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'metakey', MSText(), primary_key=False, nullable=False),
            Column(u'metadesc', MSText(), primary_key=False, nullable=False),
            Column(u'access', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'metadata', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'idx_access', jos_content.c.access, unique=False)
Index(u'idx_checkout', jos_content.c.checked_out, unique=False)
Index(u'idx_state', jos_content.c.state, unique=False)
Index(u'idx_catid', jos_content.c.catid, unique=False)
Index(u'idx_createdby', jos_content.c.created_by, unique=False)
Index(u'idx_section', jos_content.c.sectionid, unique=False)


jos_content_frontpage =  Table('jos_content_frontpage', metadata,
    Column(u'content_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_content_rating =  Table('jos_content_rating', metadata,
    Column(u'content_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'rating_sum', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rating_count', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'lastip', MSString(length=50), primary_key=False, nullable=False),
    
    
    )


jos_core_acl_aro =  Table('jos_core_acl_aro', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'section_value', MSString(length=240), primary_key=False, nullable=False),
            Column(u'value', MSString(length=240), primary_key=False, nullable=False),
            Column(u'order_value', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'hidden', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'jos_section_value_value_aro', jos_core_acl_aro.c.section_value, jos_core_acl_aro.c.value, unique=True)
Index(u'jos_gacl_hidden_aro', jos_core_acl_aro.c.hidden, unique=False)


jos_core_acl_aro_groups =  Table('jos_core_acl_aro_groups', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'lft', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rgt', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'value', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'jos_gacl_parent_id_aro_groups', jos_core_acl_aro_groups.c.parent_id, unique=False)
Index(u'jos_gacl_lft_rgt_aro_groups', jos_core_acl_aro_groups.c.lft, jos_core_acl_aro_groups.c.rgt, unique=False)


jos_core_acl_aro_map =  Table('jos_core_acl_aro_map', metadata,
    Column(u'acl_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'section_value', MSString(length=230), primary_key=True, nullable=False),
            Column(u'value', MSString(length=100), primary_key=True, nullable=False),
    
    
    )


jos_core_acl_aro_sections =  Table('jos_core_acl_aro_sections', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'value', MSString(length=230), primary_key=False, nullable=False),
            Column(u'order_value', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=230), primary_key=False, nullable=False),
            Column(u'hidden', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'jos_gacl_value_aro_sections', jos_core_acl_aro_sections.c.value, unique=True)
Index(u'jos_gacl_hidden_aro_sections', jos_core_acl_aro_sections.c.hidden, unique=False)


jos_core_acl_groups_aro_map =  Table('jos_core_acl_groups_aro_map', metadata,
    Column(u'group_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'section_value', MSString(length=240), primary_key=False, nullable=False),
            Column(u'aro_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'group_id_aro_id_groups_aro_map', jos_core_acl_groups_aro_map.c.group_id, jos_core_acl_groups_aro_map.c.section_value, jos_core_acl_groups_aro_map.c.aro_id, unique=True)


jos_core_log_items =  Table('jos_core_log_items', metadata,
    Column(u'time_stamp', MSDate(), primary_key=False, nullable=False),
            Column(u'item_table', MSString(length=50), primary_key=False, nullable=False),
            Column(u'item_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_core_log_searches =  Table('jos_core_log_searches', metadata,
    Column(u'search_term', MSString(length=128), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_docman =  Table('jos_docman', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'dmname', MSText(), primary_key=False, nullable=False),
            Column(u'dmdescription', MSLongText(), primary_key=False),
            Column(u'dmdate_published', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'dmowner', MSInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'dmfilename', MSText(), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'dmurl', MSText(), primary_key=False),
            Column(u'dmcounter', MSInteger(display_width=11), primary_key=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'approved', MSBoolean(), primary_key=False, nullable=False),
            Column(u'dmthumbnail', MSText(), primary_key=False),
            Column(u'dmlastupdateon', MSDateTime(timezone=False), primary_key=False),
            Column(u'dmlastupdateby', MSInteger(display_width=5), primary_key=False, nullable=False),
            Column(u'dmsubmitedby', MSInteger(display_width=5), primary_key=False, nullable=False),
            Column(u'dmmantainedby', MSInteger(display_width=5), primary_key=False),
            Column(u'dmlicense_id', MSInteger(display_width=5), primary_key=False),
            Column(u'dmlicense_display', MSBoolean(), primary_key=False, nullable=False),
            Column(u'access', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'attribs', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'pub_appr_own_cat_name', jos_docman.c.published, jos_docman.c.approved, jos_docman.c.dmowner, jos_docman.c.catid, jos_docman.c.dmname, unique=False)
Index(u'appr_pub_own_cat_date', jos_docman.c.approved, jos_docman.c.published, jos_docman.c.dmowner, jos_docman.c.catid, jos_docman.c.dmdate_published, unique=False)
Index(u'own_pub_appr_cat_count', jos_docman.c.dmowner, jos_docman.c.published, jos_docman.c.approved, jos_docman.c.catid, jos_docman.c.dmcounter, unique=False)
Index(u'own_pub_appr_cat_id', jos_docman.c.dmowner, jos_docman.c.published, jos_docman.c.approved, jos_docman.c.catid, jos_docman.c.id, unique=False)


jos_docman_groups =  Table('jos_docman_groups', metadata,
    Column(u'groups_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'groups_name', MSText(), primary_key=False, nullable=False),
            Column(u'groups_description', MSLongText(), primary_key=False),
            Column(u'groups_access', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'groups_members', MSText(), primary_key=False),
    
    
    )


jos_docman_history =  Table('jos_docman_history', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'doc_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'revision', MSInteger(display_width=5), primary_key=False, nullable=False),
            Column(u'his_date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'his_who', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'his_obs', MSLongText(), primary_key=False),
    
    
    )


jos_docman_licenses =  Table('jos_docman_licenses', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSText(), primary_key=False, nullable=False),
            Column(u'license', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_docman_log =  Table('jos_docman_log', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'log_docid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'log_ip', MSText(), primary_key=False, nullable=False),
            Column(u'log_datetime', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'log_user', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'log_browser', MSText(), primary_key=False),
            Column(u'log_os', MSText(), primary_key=False),
    
    
    )


jos_fb_announcement =  Table('jos_fb_announcement', metadata,
    Column(u'id', MSInteger(display_width=3), primary_key=True, nullable=False),
            Column(u'title', MSTinyText(), primary_key=False),
            Column(u'sdescription', MSText(), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'created', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'ordering', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'showdate', MSBoolean(), primary_key=False, nullable=False),
    
    
    )


jos_fb_attachments =  Table('jos_fb_attachments', metadata,
    Column(u'mesid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'filelocation', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'mesid', jos_fb_attachments.c.mesid, unique=False)


jos_fb_categories =  Table('jos_fb_categories', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent', MSInteger(display_width=11), primary_key=False),
            Column(u'name', MSTinyText(), primary_key=False),
            Column(u'cat_emoticon', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'locked', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'alert_admin', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'moderated', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'moderators', MSString(length=15), primary_key=False),
            Column(u'pub_access', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'pub_recurse', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'admin_access', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'admin_recurse', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'ordering', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'future2', MSInteger(display_width=11), primary_key=False),
            Column(u'published', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'checked_out', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'review', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'headerdesc', MSText(), primary_key=False, nullable=False),
            Column(u'class_sfx', MSString(length=20), primary_key=False, nullable=False),
            Column(u'id_last_msg', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'numTopics', MSMediumInteger(display_width=8), primary_key=False, nullable=False),
            Column(u'numPosts', MSMediumInteger(display_width=8), primary_key=False, nullable=False),
            Column(u'time_last_msg', MSInteger(display_width=11), primary_key=False),
    
    
    )
Index(u'parent', jos_fb_categories.c.parent, unique=False)
Index(u'published_pubaccess_id', jos_fb_categories.c.published, jos_fb_categories.c.pub_access, jos_fb_categories.c.id, unique=False)
Index(u'msg_id', jos_fb_categories.c.id_last_msg, unique=False)


jos_fb_favorites =  Table('jos_fb_favorites', metadata,
    Column(u'thread', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'userid', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'thread', jos_fb_favorites.c.thread, unique=False)
Index(u'userid', jos_fb_favorites.c.userid, unique=False)


jos_fb_groups =  Table('jos_fb_groups', metadata,
    Column(u'id', MSInteger(display_width=4), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False),
    
    
    )


jos_fb_messages =  Table('jos_fb_messages', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent', MSInteger(display_width=11), primary_key=False),
            Column(u'thread', MSInteger(display_width=11), primary_key=False),
            Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSTinyText(), primary_key=False),
            Column(u'userid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'email', MSTinyText(), primary_key=False),
            Column(u'subject', MSTinyText(), primary_key=False),
            Column(u'time', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'ip', MSString(length=15), primary_key=False),
            Column(u'topic_emoticon', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'locked', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'hold', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False),
            Column(u'moved', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'modified_by', MSInteger(display_width=7), primary_key=False),
            Column(u'modified_time', MSInteger(display_width=11), primary_key=False),
            Column(u'modified_reason', MSTinyText(), primary_key=False),
    
    
    )
Index(u'parent', jos_fb_messages.c.parent, unique=False)
Index(u'thread', jos_fb_messages.c.thread, unique=False)
Index(u'catid', jos_fb_messages.c.catid, unique=False)
Index(u'ip', jos_fb_messages.c.ip, unique=False)
Index(u'userid', jos_fb_messages.c.userid, unique=False)
Index(u'time', jos_fb_messages.c.time, unique=False)
Index(u'locked', jos_fb_messages.c.locked, unique=False)
Index(u'hold_time', jos_fb_messages.c.hold, jos_fb_messages.c.time, unique=False)


jos_fb_messages_text =  Table('jos_fb_messages_text', metadata,
    Column(u'mesid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'message', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_fb_moderation =  Table('jos_fb_moderation', metadata,
    Column(u'catid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'userid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'future1', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'future2', MSInteger(display_width=11), primary_key=False),
    
    
    )


jos_fb_ranks =  Table('jos_fb_ranks', metadata,
    Column(u'rank_id', MSMediumInteger(display_width=8), primary_key=True, nullable=False),
            Column(u'rank_title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'rank_min', MSMediumInteger(display_width=8), primary_key=False, nullable=False),
            Column(u'rank_special', MSBoolean(), primary_key=False, nullable=False),
            Column(u'rank_image', MSString(length=255), primary_key=False, nullable=False),
    
    
    )


jos_fb_sessions =  Table('jos_fb_sessions', metadata,
    Column(u'userid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'allowed', MSText(), primary_key=False),
            Column(u'lasttime', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'readtopics', MSText(), primary_key=False),
            Column(u'currvisit', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_fb_smileys =  Table('jos_fb_smileys', metadata,
    Column(u'id', MSInteger(display_width=4), primary_key=True, nullable=False),
            Column(u'code', MSString(length=12), primary_key=False, nullable=False),
            Column(u'location', MSString(length=50), primary_key=False, nullable=False),
            Column(u'greylocation', MSString(length=60), primary_key=False, nullable=False),
            Column(u'emoticonbar', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )


jos_fb_subscriptions =  Table('jos_fb_subscriptions', metadata,
    Column(u'thread', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'userid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'future1', MSInteger(display_width=11), primary_key=False),
    
    
    )
Index(u'thread', jos_fb_subscriptions.c.thread, unique=False)
Index(u'userid', jos_fb_subscriptions.c.userid, unique=False)


jos_fb_users =  Table('jos_fb_users', metadata,
    Column(u'userid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'view', MSString(length=8), primary_key=False, nullable=False),
            Column(u'signature', MSText(), primary_key=False),
            Column(u'moderator', MSInteger(display_width=11), primary_key=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False),
            Column(u'posts', MSInteger(display_width=11), primary_key=False),
            Column(u'avatar', MSString(length=50), primary_key=False),
            Column(u'karma', MSInteger(display_width=11), primary_key=False),
            Column(u'karma_time', MSInteger(display_width=11), primary_key=False),
            Column(u'group_id', MSInteger(display_width=4), primary_key=False),
            Column(u'uhits', MSInteger(display_width=11), primary_key=False),
            Column(u'personalText', MSTinyText(), primary_key=False),
            Column(u'gender', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'birthdate', MSDate(), primary_key=False, nullable=False),
            Column(u'location', MSString(length=50), primary_key=False),
            Column(u'ICQ', MSString(length=50), primary_key=False),
            Column(u'AIM', MSString(length=50), primary_key=False),
            Column(u'YIM', MSString(length=50), primary_key=False),
            Column(u'MSN', MSString(length=50), primary_key=False),
            Column(u'SKYPE', MSString(length=50), primary_key=False),
            Column(u'GTALK', MSString(length=50), primary_key=False),
            Column(u'websitename', MSString(length=50), primary_key=False),
            Column(u'websiteurl', MSString(length=50), primary_key=False),
            Column(u'rank', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'hideEmail', MSBoolean(), primary_key=False, nullable=False),
            Column(u'showOnline', MSBoolean(), primary_key=False, nullable=False),
    
    
    )
Index(u'group_id', jos_fb_users.c.group_id, unique=False)


jos_fb_whoisonline =  Table('jos_fb_whoisonline', metadata,
    Column(u'id', MSInteger(display_width=6), primary_key=True, nullable=False),
            Column(u'userid', MSInteger(display_width=7), primary_key=False, nullable=False),
            Column(u'time', MSString(length=14), primary_key=False, nullable=False),
            Column(u'item', MSInteger(display_width=6), primary_key=False),
            Column(u'what', MSString(length=255), primary_key=False),
            Column(u'func', MSString(length=50), primary_key=False),
            Column(u'do', MSString(length=50), primary_key=False),
            Column(u'task', MSString(length=50), primary_key=False),
            Column(u'link', MSText(), primary_key=False),
            Column(u'userip', MSString(length=20), primary_key=False, nullable=False),
            Column(u'user', MSTinyInteger(display_width=2), primary_key=False, nullable=False),
    
    
    )
Index(u'userid', jos_fb_whoisonline.c.userid, unique=False)


jos_forme_config =  Table('jos_forme_config', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'setting_name', MSString(length=64), primary_key=False, nullable=False),
            Column(u'setting_value', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_forme_data =  Table('jos_forme_data', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'form_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'date_added', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'uip', MSString(length=15), primary_key=False, nullable=False),
            Column(u'uid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'lang', MSString(length=10), primary_key=False, nullable=False),
    
    
    )


jos_forme_fields =  Table('jos_forme_fields', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'form_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'fieldstyle', MSText(), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'inputtype', MSString(length=255), primary_key=False, nullable=False),
            Column(u'default_value', MSText(), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'validation_rule', MSString(length=50), primary_key=False, nullable=False),
            Column(u'validation_message', MSString(length=255), primary_key=False, nullable=False),
            Column(u'ordering', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )


jos_forme_forms =  Table('jos_forme_forms', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'formstyle', MSText(), primary_key=False, nullable=False),
            Column(u'fieldstyle', MSText(), primary_key=False, nullable=False),
            Column(u'thankyou', MSText(), primary_key=False, nullable=False),
            Column(u'email', MSText(), primary_key=False, nullable=False),
            Column(u'emailto', MSText(), primary_key=False, nullable=False),
            Column(u'emailfrom', MSString(length=255), primary_key=False, nullable=False),
            Column(u'emailfromname', MSString(length=255), primary_key=False, nullable=False),
            Column(u'emailsubject', MSString(length=255), primary_key=False, nullable=False),
            Column(u'emailmode', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'return_url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'published', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'lang', MSString(length=10), primary_key=False, nullable=False),
            Column(u'script_process', MSText(), primary_key=False, nullable=False),
            Column(u'script_display', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_groups =  Table('jos_groups', metadata,
    Column(u'id', MSTinyInteger(display_width=3), primary_key=True, nullable=False),
            Column(u'name', MSString(length=50), primary_key=False, nullable=False),
    
    
    )


jos_joomlawatch =  Table('jos_joomlawatch', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'ip', MSString(length=255), primary_key=False),
            Column(u'country', MSChar(length=2), primary_key=False),
            Column(u'browser', MSString(length=255), primary_key=False),
    
    
    )
Index(u'ip', jos_joomlawatch.c.ip, unique=False)
Index(u'browser', jos_joomlawatch.c.browser, unique=False)


jos_joomlawatch_blocked =  Table('jos_joomlawatch_blocked', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'ip', MSString(length=255), primary_key=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False),
    
    
    )
Index(u'ip', jos_joomlawatch_blocked.c.ip, unique=False)


jos_joomlawatch_config =  Table('jos_joomlawatch_config', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'value', MSInteger(display_width=11), primary_key=False),
    
    
    )
Index(u'name', jos_joomlawatch_config.c.name, unique=False)


jos_joomlawatch_info =  Table('jos_joomlawatch_info', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'group', MSString(length=255), primary_key=False),
            Column(u'date', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'value', MSInteger(display_width=11), primary_key=False),
    
    
    )
Index(u'group', jos_joomlawatch_info.c.group, unique=False)
Index(u'name', jos_joomlawatch_info.c.name, unique=False)
Index(u'date', jos_joomlawatch_info.c.date, unique=False)


jos_joomlawatch_ip2c =  Table('jos_joomlawatch_ip2c', metadata,
    Column(u'start', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'end', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'a2', MSChar(length=2), primary_key=False, nullable=False),
            Column(u'a3', MSChar(length=3), primary_key=False, nullable=False),
            Column(u'country', MSString(length=100), primary_key=False, nullable=False),
    
    
    )


jos_joomlawatch_uri =  Table('jos_joomlawatch_uri', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'fk', MSInteger(display_width=11), primary_key=False),
            Column(u'timestamp', MSInteger(display_width=11), primary_key=False),
            Column(u'uri', MSString(length=255), primary_key=False),
            Column(u'title', MSString(length=255), primary_key=False),
    
    
    )
Index(u'timestamp', jos_joomlawatch_uri.c.timestamp, unique=False)


jos_mambowiki =  Table('jos_mambowiki', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'showmediawikiimage', MSInteger(display_width=4), primary_key=False),
            Column(u'height', MSInteger(display_width=4), primary_key=False),
            Column(u'px', MSInteger(display_width=4), primary_key=False),
            Column(u'usescrollbars', MSInteger(display_width=4), primary_key=False),
            Column(u'ordering', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False),
            Column(u'uninstallwikitables', MSInteger(display_width=4), primary_key=False),
            Column(u'uninstallmambowikirows', MSInteger(display_width=4), primary_key=False),
            Column(u'readaccessrules', MSInteger(display_width=4), primary_key=False),
            Column(u'editaccessrules', MSInteger(display_width=4), primary_key=False),
    
    
    )
Index(u'ordering', jos_mambowiki.c.ordering, unique=False)


jos_menu =  Table('jos_menu', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'menutype', MSString(length=75), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link', MSText(), primary_key=False),
            Column(u'type', MSString(length=50), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'parent', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'componentid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'sublevel', MSInteger(display_width=11), primary_key=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'pollid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'browserNav', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'utaccess', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'lft', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rgt', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'home', MSInteger(display_width=1), primary_key=False, nullable=False),
    
    
    )
Index(u'componentid', jos_menu.c.componentid, jos_menu.c.menutype, jos_menu.c.published, jos_menu.c.access, unique=False)
Index(u'menutype', jos_menu.c.menutype, unique=False)


jos_menu_types =  Table('jos_menu_types', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'menutype', MSString(length=75), primary_key=False, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'description', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'menutype', jos_menu_types.c.menutype, unique=True)


jos_messages =  Table('jos_messages', metadata,
    Column(u'message_id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'user_id_from', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'user_id_to', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'folder_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'date_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'state', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'priority', MSInteger(display_width=1), primary_key=False, nullable=False),
            Column(u'subject', MSText(), primary_key=False, nullable=False),
            Column(u'message', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'useridto_state', jos_messages.c.user_id_to, jos_messages.c.state, unique=False)


jos_messages_cfg =  Table('jos_messages_cfg', metadata,
    Column(u'user_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'cfg_name', MSString(length=100), primary_key=False, nullable=False),
            Column(u'cfg_value', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'idx_user_var_name', jos_messages_cfg.c.user_id, jos_messages_cfg.c.cfg_name, unique=True)


jos_migration_backlinks =  Table('jos_migration_backlinks', metadata,
    Column(u'itemid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=100), primary_key=False, nullable=False),
            Column(u'url', MSText(), primary_key=False, nullable=False),
            Column(u'sefurl', MSText(), primary_key=False, nullable=False),
            Column(u'newurl', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_modules =  Table('jos_modules', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSText(), primary_key=False, nullable=False),
            Column(u'content', MSText(), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'position', MSString(length=50), primary_key=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'module', MSString(length=50), primary_key=False),
            Column(u'numnews', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'showtitle', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'iscore', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'client_id', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'control', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'published', jos_modules.c.published, jos_modules.c.access, unique=False)
Index(u'newsfeeds', jos_modules.c.module, jos_modules.c.published, unique=False)


jos_modules_menu =  Table('jos_modules_menu', metadata,
    Column(u'moduleid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'menuid', MSInteger(display_width=11), primary_key=True, nullable=False),
    
    
    )


jos_mxc_admcomments =  Table('jos_mxc_admcomments', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'contentid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=30), primary_key=False, nullable=False),
            Column(u'title', MSString(length=50), primary_key=False, nullable=False),
            Column(u'comment', MSText(), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'iduser', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rating', MSTinyInteger(display_width=2), primary_key=False, nullable=False),
            Column(u'currentlevelrating', MSTinyInteger(display_width=2), primary_key=False, nullable=False),
            Column(u'component', MSString(length=50), primary_key=False, nullable=False),
    
    
    )


jos_mxc_badwords =  Table('jos_mxc_badwords', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'badword', MSString(length=20), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
    
    
    )


jos_mxc_blockip =  Table('jos_mxc_blockip', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'ipblock', MSString(length=15), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
    
    
    )


jos_mxc_comments =  Table('jos_mxc_comments', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parentid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'status', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'contentid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'ip', MSString(length=15), primary_key=False, nullable=False),
            Column(u'name', MSString(length=30), primary_key=False, nullable=False),
            Column(u'web', MSString(length=255), primary_key=False, nullable=False),
            Column(u'email', MSString(length=255), primary_key=False, nullable=False),
            Column(u'title', MSString(length=50), primary_key=False, nullable=False),
            Column(u'comment', MSText(), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'iduser', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'subscribe', MSBoolean(), primary_key=False, nullable=False),
            Column(u'rating', MSTinyInteger(display_width=2), primary_key=False, nullable=False),
            Column(u'currentlevelrating', MSTinyInteger(display_width=2), primary_key=False, nullable=False),
            Column(u'lang', MSString(length=10), primary_key=False, nullable=False),
            Column(u'component', MSString(length=50), primary_key=False, nullable=False),
    
    
    )


jos_mxc_favoured =  Table('jos_mxc_favoured', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'id_content', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'id_user', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'ip', MSString(length=15), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )


jos_newsfeeds =  Table('jos_newsfeeds', metadata,
    Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSText(), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link', MSText(), primary_key=False, nullable=False),
            Column(u'filename', MSString(length=200), primary_key=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'numarticles', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'cache_time', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'rtl', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )
Index(u'published', jos_newsfeeds.c.published, unique=False)
Index(u'catid', jos_newsfeeds.c.catid, unique=False)


jos_plugins =  Table('jos_plugins', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=100), primary_key=False, nullable=False),
            Column(u'element', MSString(length=100), primary_key=False, nullable=False),
            Column(u'folder', MSString(length=100), primary_key=False, nullable=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'published', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'iscore', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'client_id', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'idx_folder', jos_plugins.c.published, jos_plugins.c.client_id, jos_plugins.c.access, jos_plugins.c.folder, unique=False)


jos_poll_data =  Table('jos_poll_data', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'pollid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'text', MSText(), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'pollid', jos_poll_data.c.pollid, jos_poll_data.c.text, unique=False)


jos_poll_date =  Table('jos_poll_date', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'vote_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'poll_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'poll_id', jos_poll_date.c.poll_id, unique=False)


jos_poll_menu =  Table('jos_poll_menu', metadata,
    Column(u'pollid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'menuid', MSInteger(display_width=11), primary_key=True, nullable=False),
    
    
    )


jos_polls =  Table('jos_polls', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'voters', MSInteger(display_width=9), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'access', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'lag', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_rd_rss =  Table('jos_rd_rss', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'catids', MSText(), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'created', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'created_by', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'modified', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'modified_by', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'state', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )


jos_redirect =  Table('jos_redirect', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'original', MSString(length=255), primary_key=False, nullable=False),
            Column(u'redirect', MSString(length=255), primary_key=False, nullable=False),
            Column(u'error_code', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_sections =  Table('jos_sections', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'image', MSText(), primary_key=False, nullable=False),
            Column(u'scope', MSString(length=50), primary_key=False, nullable=False),
            Column(u'image_position', MSString(length=30), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'access', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'count', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'idx_scope', jos_sections.c.scope, unique=False)


jos_serrbizsef_components =  Table('jos_serrbizsef_components', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'com_name', MSString(length=100), primary_key=False, nullable=False),
            Column(u'format', MSString(length=50), primary_key=False, nullable=False),
            Column(u'user_specific_name', MSString(length=50), primary_key=False, nullable=False),
            Column(u'default_name', MSString(length=50), primary_key=False, nullable=False),
            Column(u'status', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )


jos_serrbizsef_config =  Table('jos_serrbizsef_config', metadata,
    Column(u'active', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'override_meta', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'sef_status', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'allow_redirect', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'custom_error_page', MSString(length=150), primary_key=False),
    
    
    )


jos_serrbizsef_sef =  Table('jos_serrbizsef_sef', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'joom_original', MSString(length=250), primary_key=False, nullable=False),
            Column(u'sb_sef', MSString(length=250), primary_key=False, nullable=False),
            Column(u'title', MSString(length=250), primary_key=False, nullable=False),
            Column(u'meta_title', MSString(length=250), primary_key=False, nullable=False),
            Column(u'meta_description', MSString(length=250), primary_key=False, nullable=False),
            Column(u'meta_keywords', MSString(length=250), primary_key=False, nullable=False),
            Column(u'component', MSString(length=60), primary_key=False, nullable=False),
            Column(u'type', MSEnum(), primary_key=False, nullable=False),
            Column(u'sbz_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'link_priority', MSEnum(), primary_key=False, nullable=False),
            Column(u'rob_index', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'follow', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'is_sef', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'is_import_sef', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'import_from', MSString(length=100), primary_key=False),
            Column(u'sef_type', MSEnum(), primary_key=False, nullable=False),
            Column(u'status', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )


jos_session =  Table('jos_session', metadata,
    Column(u'username', MSString(length=150), primary_key=False),
            Column(u'time', MSString(length=14), primary_key=False),
            Column(u'session_id', MSString(length=200), primary_key=True, nullable=False),
            Column(u'guest', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'userid', MSInteger(display_width=11), primary_key=False),
            Column(u'usertype', MSString(length=50), primary_key=False),
            Column(u'gid', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'client_id', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'data', MSLongText(), primary_key=False),
    
    
    )
Index(u'whosonline', jos_session.c.guest, jos_session.c.usertype, unique=False)
Index(u'userid', jos_session.c.userid, unique=False)
Index(u'time', jos_session.c.time, unique=False)
Index(u'blastchatc', jos_session.c.usertype, jos_session.c.guest, jos_session.c.session_id, jos_session.c.userid, unique=False)


jos_smartsef_plugins =  Table('jos_smartsef_plugins', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'published', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
            Column(u'author', MSString(length=255), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'version', MSString(length=10), primary_key=False, nullable=False),
            Column(u'author_url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'plugin', MSString(length=45), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_smartsef_router_setting =  Table('jos_smartsef_router_setting', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'router_type', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'rewrite_rule', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'component_alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'component', MSString(length=45), primary_key=False, nullable=False),
            Column(u'bypass_post_redirect', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
    
    
    )


jos_smartsef_urls =  Table('jos_smartsef_urls', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'url_sef', MSString(length=255), primary_key=False, nullable=False),
            Column(u'url_orginal', MSString(length=255), primary_key=False, nullable=False),
            Column(u'cache', MSText(), primary_key=False, nullable=False),
            Column(u'published', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'temp_key', MSString(length=10), primary_key=False, nullable=False),
            Column(u'vars', MSString(length=255), primary_key=False, nullable=False),
            Column(u'delete_locked', MSBoolean(), primary_key=False, nullable=False),
            Column(u'valid', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'remarks', MSText(), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'block_rewrite', MSBoolean(), primary_key=False, nullable=False),
            Column(u'sef_tmp_url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'url_orginal', jos_smartsef_urls.c.url_orginal, unique=False)
Index(u'url_sef', jos_smartsef_urls.c.url_sef, unique=False)


jos_stats_agents =  Table('jos_stats_agents', metadata,
    Column(u'agent', MSString(length=255), primary_key=False, nullable=False),
            Column(u'type', MSBoolean(), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )


jos_templates_menu =  Table('jos_templates_menu', metadata,
    Column(u'template', MSString(length=255), primary_key=True, nullable=False),
            Column(u'menuid', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'client_id', MSTinyInteger(display_width=4), primary_key=True, nullable=False),
    
    
    )


jos_users =  Table('jos_users', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'username', MSString(length=150), primary_key=False, nullable=False),
            Column(u'email', MSString(length=100), primary_key=False, nullable=False),
            Column(u'password', MSString(length=100), primary_key=False, nullable=False),
            Column(u'usertype', MSString(length=25), primary_key=False, nullable=False),
            Column(u'block', MSTinyInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'sendEmail', MSTinyInteger(display_width=4), primary_key=False),
            Column(u'gid', MSTinyInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'registerDate', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'lastvisitDate', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'activation', MSString(length=100), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'usertype', jos_users.c.usertype, unique=False)
Index(u'idx_name', jos_users.c.name, unique=False)
Index(u'username', jos_users.c.username, unique=False)
Index(u'email', jos_users.c.email, unique=False)
Index(u'gid_block', jos_users.c.gid, jos_users.c.block, unique=False)


jos_weblinks =  Table('jos_weblinks', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'catid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'sid', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'title', MSString(length=250), primary_key=False, nullable=False),
            Column(u'alias', MSString(length=255), primary_key=False, nullable=False),
            Column(u'url', MSString(length=250), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'published', MSBoolean(), primary_key=False, nullable=False),
            Column(u'checked_out', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'checked_out_time', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'ordering', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'archived', MSBoolean(), primary_key=False, nullable=False),
            Column(u'approved', MSBoolean(), primary_key=False, nullable=False),
            Column(u'params', MSText(), primary_key=False, nullable=False),
    
    
    )
Index(u'catid', jos_weblinks.c.catid, jos_weblinks.c.published, jos_weblinks.c.archived, unique=False)

