#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'pyzim-trunk',
 'build_date': '2011-04-28 20:10:19 +0200',
 'clean': None,
 'date': '2011-04-28 20:09:07 +0200',
 'revision_id': 'pardus@cpan.org-20110428180907-hls8utfz1nege9ji',
 'revno': 391}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
