########### GUI2Exe SVN repository information ###################
# $Date: 2009-05-15 10:52:54 +0100 (Fri, 15 May 2009) $
# $Author: andrea.gavana $
# $Revision: 57 $
# $URL: https://gui2exe.googlecode.com/svn/trunk/Setup.py $
# $Id: Setup.py 57 2009-05-15 09:52:54Z andrea.gavana $
########### GUI2Exe SVN repository information ###################


# ======================================================#
# File automagically generated by GUI2Exe version 0.1
# Andrea Gavana, 31 March 2007
# ======================================================#

# Let's start with some default (for me) imports...

from distutils.core import setup
import shutil

# Remove the build directory
shutil.rmtree("build", ignore_errors=True)

# define the manifest template
manifest_template = """
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="5.0.0.0"
    processorArchitecture="x86"
    name="GUI2Exe"
    type="win32"
/>
<description>GUI2Exe Program</description>
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="X86"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
</assembly>
"""

# ------------------- #
# py2exe target class #
# ------------------- #

class Target(object):
    """ A simple class that holds information on our executable file. """
    def __init__(self, **kw):
        """ Default class constructor. Update as you need. """
        self.__dict__.update(kw)
        # for the versioninfo resources
        self.version = "0.1"
        self.company_name = "No Company"
        self.copyright = "Andrea Gavana"
        self.name = "GUI2Exe"


# Ok, let's explain why I am doing that.
# Often, data_files, excludes and dll_excludes (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

_fpath = 'J:\\@Research\\@Python\\PyInstaller 1.5.1\\GUI2Exe_0.5.0\\GUI2Exe'
data_files = [('docs/images/icons', ['%s\\docs\\images\\icons\\exclamation.gif' % (_fpath),
                                     '%s\\docs\\images\\icons\\go.gif' % (_fpath),
                                     '%s\\docs\\images\\icons\\quote.gif' % (_fpath),
                                     '%s\\docs\\images\\icons\\stop.gif' % (_fpath)]),
              ('docs', ['%s\\docs\\switches.html' % (_fpath)]),
              ('docs/images', ['%s\\docs\\images\\arrow.gif' % (_fpath),
                               '%s\\docs\\images\\arrow2.gif' % (_fpath),
                               '%s\\docs\\images\\bg1.jpg' % (_fpath),
                               '%s\\docs\\images\\firefox.jpg' % (_fpath),
                               '%s\\docs\\images\\gui2exe_splash.png' % (_fpath),
                               '%s\\docs\\images\\gui2exe_splash2.png' % (_fpath),
                               '%s\\docs\\images\\gui2exe_splash_small.png' % (_fpath),
                               '%s\\docs\\images\\h2.gif' % (_fpath),
                               '%s\\docs\\images\\hr.gif' % (_fpath),
                               '%s\\docs\\images\\img-1.jpg' % (_fpath),
                               '%s\\docs\\images\\img-2.jpg' % (_fpath),
                               '%s\\docs\\images\\logo.gif' % (_fpath),
                               '%s\\docs\\images\\nav_btm.jpg' % (_fpath),
                               '%s\\docs\\images\\nav_side.jpg' % (_fpath),
                               '%s\\docs\\images\\splash_small.png' % (_fpath),
                               '%s\\docs\\images\\switches.png' % (_fpath)]),
              ('docs/images/bg', ['%s\\docs\\images\\bg\\balloons.gif' % (_fpath),
                                  '%s\\docs\\images\\bg\\bullet.gif' % (_fpath),
                                  '%s\\docs\\images\\bg\\footer.jpg' % (_fpath),
                                  '%s\\docs\\images\\bg\\gradient.jpg' % (_fpath),
                                  '%s\\docs\\images\\bg\\header.jpg' % (_fpath),
                                  '%s\\docs\\images\\bg\\header_left.jpg' % (_fpath),
                                  '%s\\docs\\images\\bg\\header_right.jpg' % (_fpath)]),
              ('images', ['%s\\images\\GUI2Exe.ico' % (_fpath),
                          '%s\\images\\GUI2Exe.png' % (_fpath),
                          '%s\\images\\PyInstaller.png' % (_fpath),
                          '%s\\images\\about.png' % (_fpath),
                          '%s\\images\\api_reference.png' % (_fpath),
                          '%s\\images\\aui_config.png' % (_fpath),
                          '%s\\images\\binarydependencies.png' % (_fpath),
                          '%s\\images\\bitmap.png' % (_fpath),
                          '%s\\images\\clear_all.png' % (_fpath),
                          '%s\\images\\code_discard.png' % (_fpath),
                          '%s\\images\\code_save.png' % (_fpath),
                          '%s\\images\\compile.png' % (_fpath),
                          '%s\\images\\compiler_switches.png' % (_fpath),
                          '%s\\images\\custom_code.png' % (_fpath),
                          '%s\\images\\cx_Freeze.png' % (_fpath),
                          '%s\\images\\datafiles.png' % (_fpath),
                          '%s\\images\\delete_all.png' % (_fpath),
                          '%s\\images\\delete_project.png' % (_fpath),
                          '%s\\images\\delete_selected.png' % (_fpath),
                          '%s\\images\\dllicon.png' % (_fpath),
                          '%s\\images\\drag_n_drop.png' % (_fpath),
                          '%s\\images\\dry.png' % (_fpath),
                          '%s\\images\\exit.png' % (_fpath),
                          '%s\\images\\export_setup.png' % (_fpath),
                          '%s\\images\\gui2exe_splash.png' % (_fpath),
                          '%s\\images\\help.png' % (_fpath),
                          '%s\\images\\history_clear.png' % (_fpath),
                          '%s\\images\\icon.png' % (_fpath),
                          '%s\\images\\kill.png' % (_fpath),
                          '%s\\images\\load_project.png' % (_fpath),
                          '%s\\images\\message_compile.png' % (_fpath),
                          '%s\\images\\message_copy.png' % (_fpath),
                          '%s\\images\\message_error.png' % (_fpath),
                          '%s\\images\\message_find.png' % (_fpath),
                          '%s\\images\\message_info.png' % (_fpath),
                          '%s\\images\\message_warning.png' % (_fpath),
                          '%s\\images\\missingmodules.png' % (_fpath),
                          '%s\\images\\modules.png' % (_fpath),
                          '%s\\images\\packages.png' % (_fpath),
                          '%s\\images\\project.png' % (_fpath),
                          '%s\\images\\project_broken.png' % (_fpath),
                          '%s\\images\\project_edit.png' % (_fpath),
                          '%s\\images\\project_home.png' % (_fpath),
                          '%s\\images\\project_ok.png' % (_fpath),
                          '%s\\images\\project_unsaved.png' % (_fpath),
                          '%s\\images\\py2app.png' % (_fpath),
                          '%s\\images\\py2exe.png' % (_fpath),
                          '%s\\images\\resource.png' % (_fpath),
                          '%s\\images\\restore_aui.png' % (_fpath),
                          '%s\\images\\runexe.png' % (_fpath),
                          '%s\\images\\save_aui_config.png' % (_fpath),
                          '%s\\images\\save_project.png' % (_fpath),
                          '%s\\images\\sort_down.png' % (_fpath),
                          '%s\\images\\sort_up.png' % (_fpath),
                          '%s\\images\\switch_db.png' % (_fpath),
                          '%s\\images\\tips_and_tricks.png' % (_fpath),
                          '%s\\images\\upgrade.png' % (_fpath),
                          '%s\\images\\view_setup.png' % (_fpath)]),
              ('docs/css', ['%s\\docs\\css\\html.css' % (_fpath),
                            '%s\\docs\\css\\layout.css' % (_fpath),
                            '%s\\docs\\css\\print.css' % (_fpath)])]

includes = []
excludes = ['Tkconstants', 'Tkinter', '_gtkagg', '_tkagg', 'curses',
            'email', 'pywin.debugger', 'pywin.debugger.dbgcon',
            'pywin.dialogs', 'tcl']
packages = []
dll_excludes = ['libgdk-win32-2.0-0.dll', 'libgobject-2.0-0.dll', 'tcl84.dll',
                'tk84.dll']
icon_resources = [(1, '%s\\images\\GUI2Exe.ico' % (_fpath))]
bitmap_resources = []
other_resources = [(24, 1, manifest_template)]


# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# Ok, now we are going to build our target class.
# I chose this building strategy as it works perfectly for me :-D

test_wx = Target(
    # what to build
    script = "GUI2Exe.py",
    icon_resources = icon_resources,
    bitmap_resources = bitmap_resources,
    other_resources = other_resources
    )


# That's serious now: we have all (or almost all) the options py2exe
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.

setup(

    data_files = data_files,

    options = {"py2exe": {"compressed": 2, 
                          "optimize": 2,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dll_excludes": dll_excludes,
                          "bundle_files": 1,
                          "dist_dir": "dist",
                          "xref": False,
                          "skip_archive": False,
                          "ascii": False,
                          "custom_boot_script": '',
                         }
              },

    zipfile = None,
    windows = [test_wx]
    )


# And we are done. That's a setup script :-D

