# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcget_registered_dialog(wx.Dialog):
#!XRCED:begin-block:xrcget_registered_dialog.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcget_registered_dialog.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "get_registered_dialog")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_BUTTON, self.OnButton_close, id=xrc.XRCID('close'))

#!XRCED:begin-block:xrcget_registered_dialog.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcget_registered_dialog.OnClose        

#!XRCED:begin-block:xrcget_registered_dialog.OnButton_close
    def OnButton_close(self, evt):
        # Replace with event handler code
        print "OnButton_close()"
#!XRCED:end-block:xrcget_registered_dialog.OnButton_close        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    get_registered_dialog_xrc = '''\
<?xml version="1.0" ?>
<resource>
  <object class="wxDialog" name="get_registered_dialog">
    <size>400,300</size>
    <title>Get Registered</title>
    <centered>1</centered>
    <style>wxSTAY_ON_TOP|wxCLOSE_BOX</style>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBitmap"/>
      </object>
      <object class="sizeritem">
        <object class="wxStaticText" name="s_text">
          <label>some text goes here</label>
          <wrap>0</wrap>
          <style>wxALIGN_LEFT</style>
        </object>
      </object>
      <object class="sizeritem">
        <object class="wxButton" name="close">
          <label>Dismiss</label>
          <XRCED>
            <events>EVT_BUTTON</events>
          </XRCED>
        </object>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/get_registered_dialog/get_registered_dialog_xrc', get_registered_dialog_xrc)
    __res.Load('memory:XRC/get_registered_dialog/get_registered_dialog_xrc')

