#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Aug 02 16:26:15 2008

import wx
from wx.lib.wordwrap import wordwrap

# begin wxGlade: extracode
# end wxGlade

licenseText = "blah " * 250 + "\n\n" +"yadda " * 100

class MyAboutPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyAboutPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyAboutPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyAboutPanel.__do_layout
        pass
        # end wxGlade

# end of class MyAboutPanel


class TopFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TopFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.top_frame_menubar = wx.MenuBar()
        self.file_menu_item = wx.Menu()
        self.open_menu_item = wx.MenuItem(self.file_menu_item, wx.NewId(), "Open", "", wx.ITEM_NORMAL)
        self.file_menu_item.AppendItem(self.open_menu_item)
        self.top_frame_menubar.Append(self.file_menu_item, "File")
        self.help_menu_item = wx.Menu()
        self.about_menu_item = wx.MenuItem(self.help_menu_item, wx.NewId(), "About", "", wx.ITEM_NORMAL)
        self.help_menu_item.AppendItem(self.about_menu_item)
        self.top_frame_menubar.Append(self.help_menu_item, "Help")
        self.SetMenuBar(self.top_frame_menubar)
        # Menu Bar end
        self.top_frame_statusbar = self.CreateStatusBar(2, 0)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("Z:\\python projects\\wxPython2.8 Docs and Demos\\samples\\pydocview\\splash.png", wx.BITMAP_TYPE_ANY))
        self.gauge_1 = wx.Gauge(self, -1, 10)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onFileOpen, self.open_menu_item)
        self.Bind(wx.EVT_MENU, self.onAbout, self.about_menu_item)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TopFrame.__set_properties
        self.SetTitle("PDFexporter v1.0")
        self.SetSize((800, 600))
        self.top_frame_statusbar.SetStatusWidths([-3, -1])
        # statusbar fields
        top_frame_statusbar_fields = ["top_frame_statusbar", "field2"]
        for i in range(len(top_frame_statusbar_fields)):
            self.top_frame_statusbar.SetStatusText(top_frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TopFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.bitmap_1, 0, 0, 0)
        sizer_1.Add(self.gauge_1, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def onAbout(self, event): # wxGlade: TopFrame.<event_handler>
        info = wx.AboutDialogInfo()
        info.Name = "Hello World"
        info.Version = "1.2.3"
        info.Copyright = "(C) 2006 Programmers and Coders Everywhere"
        info.Description = wordwrap(
            "A \"hello world\" program is a software program that prints out "
            "\"Hello world!\" on a display device. It is used in many introductory "
            "tutorials for teaching a programming language."
            
            "\n\nSuch a program is typically one of the simplest programs possible "
            "in a computer language. A \"hello world\" program can be a useful "
            "sanity test to make sure that a language's compiler, development "
            "environment, and run-time environment are correctly installed.",
            350, wx.ClientDC(self))
        info.WebSite = ("http://en.wikipedia.org/wiki/Hello_world", "Hello World home page")
        info.Developers = [ "Joe Programmer",
                            "Jane Coder",
                            "Vippy the Mascot" ]

        info.License = wordwrap(licenseText, 500, wx.ClientDC(self))

        # Then we call wx.AboutBox giving it that info object
        wx.AboutBox(info)

    def onFileOpen(self, event): # wxGlade: TopFrame.<event_handler>
        print "Event handler `onFileOpen' not implemented"
        event.Skip()

# end of class TopFrame


class PDFexporter(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = TopFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class PDFexporter

if __name__ == "__main__":
    PDCexporter = PDFexporter(0)
    PDCexporter.MainLoop()
