application: vyperlogixcorp
version: 49
runtime: python
api_version: 1
threadsafe: false
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bat)|
 (.*\.txt)|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 (@templates)|
 )$

default_expiration: '3650d'

handlers:
- url: /_ah/queue/hothandler/.*
  script: hothandler.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media/.*
  script: secureZipServe.py

- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico
  mime_type: image/x-icon 

- url: /crossdomain.xml
  static_files: media/crossdomain.xml
  upload: media/crossdomain.xml
  mime_type: text/xml 

- url: /global-nav
  static_dir: global-nav

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional

- url: /rocket/.*
  script: rocket/rocket.py
