""" make_metadata_gui.py --

 UI generated by GUI Builder Build 146 on 2007-09-06 11:40:16 from:
    Z:/python projects/reports_development/make_metadata_gui.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from make_metadata_gui_ui import Make_metadata_gui

# BEGIN USER CODE global

# END USER CODE global

class CustomMake_metadata_gui(Make_metadata_gui):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _scale_1_command --
    #
    # Callback to handle _scale_1 widget option -command
    def _scale_1_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomMake_metadata_gui(root)
    root.title('make_metadata_gui')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
