# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/
from sqlalchemy import *
from sqlalchemy.databases.mysql import *
metadata = MetaData()
content_content =  Table('content_content', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'menutype_id', MSString(length=10), primary_key=False, nullable=False),
            Column(u'admin_mode', MSBoolean(), primary_key=False, nullable=False),
            Column(u'url', MSString(length=128), primary_key=False, nullable=False),
            Column(u'descr', MSString(length=128), primary_key=False),
            Column(u'menu_tag', MSString(length=30), primary_key=False, nullable=False),
            Column(u'target', MSString(length=30), primary_key=False),
            Column(u'content', MSLongText(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'menutype_id'], [u'vyperlogix2.content_menutype.menutype'], name=u'menutype_id_refs_menutype_41796a94'),
    
    )
Index(u'content_content_menutype_id', content_content.c.menutype_id, unique=False)
content_content_sites =  Table('content_content_sites', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'content_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'content_id', content_content_sites.c.content_id, content_content_sites.c.site_id, unique=True)
content_country =  Table('content_country', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'iso', MSString(length=2), primary_key=False, nullable=False),
            Column(u'name', MSString(length=80), primary_key=False, nullable=False),
            Column(u'printable_name', MSString(length=80), primary_key=False, nullable=False),
            Column(u'iso3', MSString(length=3), primary_key=False, nullable=False),
            Column(u'numcode', MSSmallInteger(display_width=6), primary_key=False, nullable=False),
    
    
    )
content_cssnode =  Table('content_cssnode', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'nodeType_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=64), primary_key=False, nullable=False),
            Column(u'value', MSString(length=256), primary_key=False, nullable=False),
    
    
    )
Index(u'content_cssnode_parent_id', content_cssnode.c.parent_id, unique=False)
Index(u'content_cssnode_site_id', content_cssnode.c.site_id, unique=False)
Index(u'content_cssnode_nodeType_id', content_cssnode.c.nodeType_id, unique=False)
content_cssnodetype =  Table('content_cssnodetype', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=16), primary_key=False, nullable=False),
    
    
    )
content_cssparent =  Table('content_cssparent', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'snippet_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=64), primary_key=False, nullable=False),
    
    
    )
Index(u'content_cssparent_snippet_id', content_cssparent.c.snippet_id, unique=False)
content_image =  Table('content_image', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'image', MSString(length=100), primary_key=False, nullable=False),
    
    
    )
Index(u'content_image_site_id', content_image.c.site_id, unique=False)
content_menutype =  Table('content_menutype', metadata,
    Column(u'menutype', MSString(length=10), primary_key=True, nullable=False),
            Column(u'descr', MSString(length=128), primary_key=False, nullable=False),
    
    
    )
content_role =  Table('content_role', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=40), primary_key=False, nullable=False),
    
    
    )
content_sitename =  Table('content_sitename', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'user_id', MSString(length=75), primary_key=False, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'user_id'], [u'vyperlogix2.content_user.email_address'], name=u'user_id_refs_email_address_5aab8d78'),
    
    )
Index(u'content_sitename_user_id', content_sitename.c.user_id, unique=False)
Index(u'content_sitename_site_id', content_sitename.c.site_id, unique=False)
content_snippet =  Table('content_snippet', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'snippet_type_id', MSString(length=30), primary_key=False, nullable=False),
            Column(u'descr', MSString(length=128), primary_key=False),
            Column(u'snippet_tag', MSString(length=128), primary_key=False, nullable=False),
            Column(u'content', MSLongText(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'snippet_type_id'], [u'vyperlogix2.content_snippettype.snippet_type'], name=u'snippet_type_id_refs_snippet_type_4cd2105d'),
    
    )
Index(u'content_snippet_snippet_type_id', content_snippet.c.snippet_type_id, unique=False)
content_snippet_sites =  Table('content_snippet_sites', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'snippet_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'snippet_id', content_snippet_sites.c.snippet_id, content_snippet_sites.c.site_id, unique=True)
content_snippettype =  Table('content_snippettype', metadata,
    Column(u'admin', MSBoolean(), primary_key=False, nullable=False),
            Column(u'snippet_type', MSString(length=30), primary_key=True, nullable=False),
            Column(u'descr', MSString(length=128), primary_key=False, nullable=False),
    
    
    )
content_state =  Table('content_state', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=40), primary_key=False, nullable=False),
            Column(u'abbrev', MSString(length=2), primary_key=False, nullable=False),
    
    
    )
content_url =  Table('content_url', metadata,
    Column(u'url', MSString(length=255), primary_key=True, nullable=False),
            Column(u'descr', MSString(length=128), primary_key=False),
            Column(u'url_tag', MSString(length=30), primary_key=False, nullable=False),
    
    
    )
content_url_sites =  Table('content_url_sites', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'url_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'site_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'url_id', content_url_sites.c.url_id, content_url_sites.c.site_id, unique=True)
content_user =  Table('content_user', metadata,
    Column(u'role_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'referred_by_id', MSString(length=128), primary_key=False),
            Column(u'companyname', MSString(length=30), primary_key=False),
            Column(u'firstname', MSString(length=30), primary_key=False, nullable=False),
            Column(u'lastname', MSString(length=30), primary_key=False, nullable=False),
            Column(u'email_address', MSString(length=75), primary_key=True, nullable=False),
            Column(u'password', MSString(length=100), primary_key=False),
            Column(u'street_address', MSString(length=60), primary_key=False),
            Column(u'city', MSString(length=30), primary_key=False),
            Column(u'state_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'country_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'zipcode', MSString(length=30), primary_key=False),
            Column(u'phone_number', MSString(length=20), primary_key=False),
            Column(u'activated', MSBoolean(), primary_key=False, nullable=False),
            Column(u'activated_on', MSDateTime(timezone=False), primary_key=False),
    ForeignKeyConstraint([u'country_id'], [u'vyperlogix2.content_country.id'], name=u'country_id_refs_id_7f5ec229'),
            ForeignKeyConstraint([u'state_id'], [u'vyperlogix2.content_state.id'], name=u'state_id_refs_id_c9e028'),
            ForeignKeyConstraint([u'referred_by_id'], [u'vyperlogix2.content_user.email_address'], name=u'referred_by_id_refs_email_address_eb3f6d'),
            ForeignKeyConstraint([u'role_id'], [u'vyperlogix2.content_role.id'], name=u'role_id_refs_id_14c22aa2'),
    
    )
Index(u'email_address', content_user.c.email_address, unique=True)
Index(u'content_user_role_id', content_user.c.role_id, unique=False)
Index(u'content_user_referred_by_id', content_user.c.referred_by_id, unique=False)
Index(u'content_user_country_id', content_user.c.country_id, unique=False)
Index(u'content_user_state_id', content_user.c.state_id, unique=False)
content_useractivity =  Table('content_useractivity', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'user_id', MSString(length=75), primary_key=False, nullable=False),
            Column(u'action', MSString(length=256), primary_key=False, nullable=False),
            Column(u'ip', MSChar(length=15), primary_key=False, nullable=False),
            Column(u'timestamp', MSDateTime(timezone=False), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'user_id'], [u'vyperlogix2.content_user.email_address'], name=u'user_id_refs_email_address_3b6cb2f2'),
    
    )
Index(u'content_useractivity_user_id', content_useractivity.c.user_id, unique=False)
