@echo off
START "Ruby #1" ruby doprocess.rb
START "Ruby #2" ruby doprocess.rb
START "Ruby #3" ruby doprocess.rb
START "Ruby #4" ruby doprocess.rb
START "Ruby #5" ruby doprocess.rb
START "Ruby #6" ruby doprocess.rb
START "Ruby #7" ruby doprocess.rb
START "Ruby #8" ruby doprocess.rb
START "Ruby #9" ruby doprocess.rb
START "Ruby #10" ruby doprocess.rb
START "Ruby #11" ruby doprocess.rb
START "Ruby #12" ruby doprocess.rb
START "Ruby #13" ruby doprocess.rb
START "Ruby #14" ruby doprocess.rb
START "Ruby #15" ruby doprocess.rb
START "Ruby #16" ruby doprocess.rb
START "Ruby #17" ruby doprocess.rb
START "Ruby #18" ruby doprocess.rb
START "Ruby #19" ruby doprocess.rb
START "Ruby #20" ruby doprocess.rb
START "Ruby #21" ruby doprocess.rb
START "Ruby #22" ruby doprocess.rb
START "Ruby #23" ruby doprocess.rb
START "Ruby #24" ruby doprocess.rb
START "Ruby #25" ruby doprocess.rb
START "Ruby #26" ruby doprocess.rb
START "Ruby #27" ruby doprocess.rb
START "Ruby #28" ruby doprocess.rb
START "Ruby #29" ruby doprocess.rb
START "Ruby #30" ruby doprocess.rb
START "Ruby #41" ruby doprocess.rb
START "Ruby #42" ruby doprocess.rb
START "Ruby #43" ruby doprocess.rb
START "Ruby #44" ruby doprocess.rb
START "Ruby #45" ruby doprocess.rb
START "Ruby #46" ruby doprocess.rb
START "Ruby #47" ruby doprocess.rb
START "Ruby #48" ruby doprocess.rb
START "Ruby #49" ruby doprocess.rb
START "Ruby #50" ruby doprocess.rb
