START "1" /HIGH run-once.cmd
START "2" /HIGH run-once.cmd
START "3" /HIGH run-once.cmd
START "4" /HIGH run-once.cmd
START "5" /HIGH run-once.cmd
START "6" /HIGH run-once.cmd
START "7" /HIGH run-once.cmd
START "8" /HIGH run-once.cmd
START "9" /HIGH run-once.cmd
START "10" /HIGH run-once.cmd

START "11" /HIGH run-once.cmd
START "12" /HIGH run-once.cmd
START "13" /HIGH run-once.cmd
START "14" /HIGH run-once.cmd
START "15" /HIGH run-once.cmd
START "16" /HIGH run-once.cmd
START "17" /HIGH run-once.cmd
START "18" /HIGH run-once.cmd
START "19" /HIGH run-once.cmd
START "20" /HIGH run-once.cmd

START "21" /HIGH run-once.cmd
START "22" /HIGH run-once.cmd
START "23" /HIGH run-once.cmd
START "24" /HIGH run-once.cmd
START "25" /HIGH run-once.cmd
START "26" /HIGH run-once.cmd
START "27" /HIGH run-once.cmd
START "28" /HIGH run-once.cmd
START "29" /HIGH run-once.cmd
START "30" /HIGH run-once.cmd
