# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/
from sqlalchemy import *
from sqlalchemy.databases.mysql import *
metadata = MetaData()
wp_DLM_CATS =  Table('wp_DLM_CATS', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'name', MSLongText(), primary_key=False, nullable=False),
            Column(u'parent', MSInteger(display_width=12), primary_key=False, nullable=False),
    
    
    )
wp_DLM_DOWNLOADS =  Table('wp_DLM_DOWNLOADS', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'title', MSString(length=200), primary_key=False, nullable=False),
            Column(u'filename', MSLongText(), primary_key=False, nullable=False),
            Column(u'file_description', MSLongText(), primary_key=False),
            Column(u'dlversion', MSString(length=200), primary_key=False, nullable=False),
            Column(u'postDate', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=12), primary_key=False, nullable=False),
            Column(u'user', MSString(length=200), primary_key=False, nullable=False),
            Column(u'category_id', MSInteger(display_width=12), primary_key=False),
            Column(u'members', MSInteger(display_width=1), primary_key=False),
            Column(u'mirrors', MSLongText(), primary_key=False),
    
    
    )
wp_DLM_FORMATS =  Table('wp_DLM_FORMATS', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'name', MSString(length=250), primary_key=False, nullable=False),
            Column(u'format', MSLongText(), primary_key=False, nullable=False),
    
    
    )
wp_DLM_LOG =  Table('wp_DLM_LOG', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'download_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'user_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'date', MSDateTime(timezone=False), primary_key=False),
            Column(u'ip_address', MSString(length=200), primary_key=False),
    
    
    )
wp_DLM_META =  Table('wp_DLM_META', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'meta_name', MSLongText(), primary_key=False, nullable=False),
            Column(u'meta_value', MSLongText(), primary_key=False, nullable=False),
            Column(u'download_id', MSInteger(display_width=12), primary_key=False, nullable=False),
    
    
    )
wp_DLM_STATS =  Table('wp_DLM_STATS', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'download_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'date', MSDate(), primary_key=False, nullable=False),
            Column(u'hits', MSInteger(display_width=12), primary_key=False, nullable=False),
    
    
    )
wp_also_bought_product =  Table('wp_also_bought_product', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'selected_product', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'associated_product', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'quantity', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
wp_cart_contents =  Table('wp_cart_contents', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'prodid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'purchaseid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'price', MSString(length=128), primary_key=False, nullable=False),
            Column(u'pnp', MSString(length=128), primary_key=False, nullable=False),
            Column(u'gst', MSString(length=128), primary_key=False, nullable=False),
            Column(u'quantity', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'donation', MSString(length=1), primary_key=False, nullable=False),
            Column(u'no_shipping', MSString(length=1), primary_key=False, nullable=False),
            Column(u'files', MSText(), primary_key=False, nullable=False),
            Column(u'meta', MSLongText(), primary_key=False),
    
    
    )
wp_cart_item_extras =  Table('wp_cart_item_extras', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'cart_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'extra_id', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
wp_cart_item_variations =  Table('wp_cart_item_variations', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'cart_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'variation_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'value_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
wp_collect_data_forms =  Table('wp_collect_data_forms', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'type', MSString(length=64), primary_key=False, nullable=False),
            Column(u'mandatory', MSString(length=1), primary_key=False, nullable=False),
            Column(u'display_log', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'default', MSString(length=128), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'order', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'order', wp_collect_data_forms.c.order, unique=False)
wp_comments =  Table('wp_comments', metadata,
    Column(u'comment_ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'comment_post_ID', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'comment_author', MSTinyText(), primary_key=False, nullable=False),
            Column(u'comment_author_email', MSString(length=100), primary_key=False, nullable=False),
            Column(u'comment_author_url', MSString(length=200), primary_key=False, nullable=False),
            Column(u'comment_author_IP', MSString(length=100), primary_key=False, nullable=False),
            Column(u'comment_date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'comment_date_gmt', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'comment_content', MSText(), primary_key=False, nullable=False),
            Column(u'comment_karma', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'comment_approved', MSString(length=20), primary_key=False, nullable=False),
            Column(u'comment_agent', MSString(length=255), primary_key=False, nullable=False),
            Column(u'comment_type', MSString(length=20), primary_key=False, nullable=False),
            Column(u'comment_parent', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'user_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'comment_approved', wp_comments.c.comment_approved, unique=False)
Index(u'comment_post_ID', wp_comments.c.comment_post_ID, unique=False)
Index(u'comment_date_gmt', wp_comments.c.comment_date_gmt, unique=False)
Index(u'comment_approved_date_gmt', wp_comments.c.comment_approved, wp_comments.c.comment_date_gmt, unique=False)
wp_currency_list =  Table('wp_currency_list', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'country', MSString(length=255), primary_key=False, nullable=False),
            Column(u'isocode', MSChar(length=2), primary_key=False),
            Column(u'currency', MSString(length=255), primary_key=False, nullable=False),
            Column(u'symbol', MSString(length=10), primary_key=False, nullable=False),
            Column(u'symbol_html', MSString(length=10), primary_key=False, nullable=False),
            Column(u'code', MSChar(length=3), primary_key=False, nullable=False),
            Column(u'has_regions', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'tax', MSString(length=8), primary_key=False, nullable=False),
            Column(u'continent', MSString(length=20), primary_key=False, nullable=False),
            Column(u'visible', MSString(length=1), primary_key=False, nullable=False),
    
    
    )
wp_dm_category =  Table('wp_dm_category', metadata,
    Column(u'id', MSInteger(display_width=3), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
wp_dm_downloads =  Table('wp_dm_downloads', metadata,
    Column(u'id', MSInteger(display_width=5), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link', MSString(length=255), primary_key=False, nullable=False),
            Column(u'icon', MSString(length=255), primary_key=False, nullable=False),
            Column(u'category', MSInteger(display_width=3), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'permissions', MSEnum(), primary_key=False, nullable=False),
            Column(u'date', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'clicks', MSInteger(display_width=6), primary_key=False, nullable=False),
    
    
    )
wp_download_status =  Table('wp_download_status', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'fileid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'purchid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'cartid', MSBigInteger(display_width=20), primary_key=False),
            Column(u'uniqueid', MSString(length=64), primary_key=False),
            Column(u'downloads', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'ip_number', MSString(length=255), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'datetime', MSDateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )
Index(u'uniqueid', wp_download_status.c.uniqueid, unique=True)
wp_gdsr_data_article =  Table('wp_gdsr_data_article', metadata,
    Column(u'post_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'rules_articles', MSChar(length=1), primary_key=False),
            Column(u'rules_comments', MSChar(length=1), primary_key=False),
            Column(u'moderate_articles', MSChar(length=1), primary_key=False),
            Column(u'moderate_comments', MSChar(length=1), primary_key=False),
            Column(u'is_page', MSChar(length=1), primary_key=False),
            Column(u'user_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'user_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
            Column(u'visitor_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
            Column(u'review', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False),
            Column(u'review_text', MSString(length=255), primary_key=False),
            Column(u'views', MSInteger(display_width=11), primary_key=False),
            Column(u'user_recc_plus', MSInteger(display_width=11), primary_key=False),
            Column(u'user_recc_minus', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_recc_plus', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_recc_minus', MSInteger(display_width=11), primary_key=False),
            Column(u'expiry_type', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'expiry_value', MSString(length=32), primary_key=False, nullable=False),
            Column(u'last_voted', MSTimeStamp(timezone=False), primary_key=False),
    
    
    )
wp_gdsr_data_category =  Table('wp_gdsr_data_category', metadata,
    Column(u'category_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'rules_articles', MSChar(length=1), primary_key=False),
            Column(u'rules_comments', MSChar(length=1), primary_key=False),
            Column(u'moderate_articles', MSChar(length=1), primary_key=False),
            Column(u'moderate_comments', MSChar(length=1), primary_key=False),
            Column(u'expiry_type', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'expiry_value', MSString(length=32), primary_key=False, nullable=False),
            Column(u'cmm_integration_set', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
wp_gdsr_data_comment =  Table('wp_gdsr_data_comment', metadata,
    Column(u'comment_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'post_id', MSInteger(display_width=11), primary_key=False),
            Column(u'is_locked', MSChar(length=1), primary_key=False),
            Column(u'user_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'user_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
            Column(u'visitor_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
            Column(u'review', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False),
            Column(u'review_text', MSString(length=255), primary_key=False),
            Column(u'user_recc_plus', MSInteger(display_width=11), primary_key=False),
            Column(u'user_recc_minus', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_recc_plus', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_recc_minus', MSInteger(display_width=11), primary_key=False),
            Column(u'last_voted', MSTimeStamp(timezone=False), primary_key=False),
    
    
    )
wp_gdsr_ips =  Table('wp_gdsr_ips', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'status', MSString(length=1), primary_key=False),
            Column(u'mode', MSString(length=1), primary_key=False),
            Column(u'ip', MSString(length=128), primary_key=False),
    
    
    )
wp_gdsr_moderate =  Table('wp_gdsr_moderate', metadata,
    Column(u'record_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'id', MSInteger(display_width=11), primary_key=False),
            Column(u'vote_type', MSString(length=10), primary_key=False),
            Column(u'multi_id', MSInteger(display_width=11), primary_key=False),
            Column(u'user_id', MSInteger(display_width=11), primary_key=False),
            Column(u'vote', MSInteger(display_width=11), primary_key=False),
            Column(u'object', MSText(), primary_key=False, nullable=False),
            Column(u'voted', MSDateTime(timezone=False), primary_key=False),
            Column(u'ip', MSString(length=32), primary_key=False),
            Column(u'user_agent', MSString(length=255), primary_key=False),
            Column(u'comment_id', MSBigInteger(display_width=20), primary_key=False),
    
    
    )
wp_gdsr_multis =  Table('wp_gdsr_multis', metadata,
    Column(u'multi_id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'name', MSString(length=64), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'stars', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'object', MSText(), primary_key=False, nullable=False),
            Column(u'weight', MSText(), primary_key=False, nullable=False),
            Column(u'auto_insert', MSString(length=4), primary_key=False, nullable=False),
            Column(u'auto_location', MSString(length=8), primary_key=False, nullable=False),
            Column(u'auto_categories', MSText(), primary_key=False, nullable=False),
            Column(u'rules', MSChar(length=1), primary_key=False),
            Column(u'moderate', MSChar(length=1), primary_key=False),
    
    
    )
wp_gdsr_multis_data =  Table('wp_gdsr_multis_data', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'post_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'multi_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'average_rating_users', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False, nullable=False),
            Column(u'average_rating_visitors', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False, nullable=False),
            Column(u'total_votes_users', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'total_votes_visitors', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'average_review', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False, nullable=False),
            Column(u'last_voted', MSTimeStamp(timezone=False), primary_key=False),
            Column(u'rules', MSChar(length=1), primary_key=False),
            Column(u'moderate', MSChar(length=1), primary_key=False),
            Column(u'expiry_type', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'expiry_value', MSString(length=32), primary_key=False, nullable=False),
    
    
    )
Index(u'post_id', wp_gdsr_multis_data.c.post_id, unique=False)
wp_gdsr_multis_trend =  Table('wp_gdsr_multis_trend', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'post_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'multi_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'vote_date', MSString(length=10), primary_key=False),
            Column(u'average_rating_users', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False, nullable=False),
            Column(u'average_rating_visitors', MSDecimal(precision=3, scale=1, asdecimal=True), primary_key=False, nullable=False),
            Column(u'total_votes_users', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'total_votes_visitors', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
wp_gdsr_multis_values =  Table('wp_gdsr_multis_values', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'source', MSString(length=3), primary_key=False, nullable=False),
            Column(u'item_id', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'user_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'user_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
            Column(u'visitor_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_votes', MSDecimal(precision=11, scale=1, asdecimal=True), primary_key=False),
    
    
    )
Index(u'id', wp_gdsr_multis_values.c.id, unique=False)
Index(u'item_id', wp_gdsr_multis_values.c.item_id, unique=False)
wp_gdsr_templates =  Table('wp_gdsr_templates', metadata,
    Column(u'template_id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'section', MSString(length=3), primary_key=False, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'elements', MSText(), primary_key=False, nullable=False),
            Column(u'dependencies', MSText(), primary_key=False, nullable=False),
            Column(u'preinstalled', MSString(length=1), primary_key=False, nullable=False),
            Column(u'default', MSString(length=1), primary_key=False, nullable=False),
    
    
    )
wp_gdsr_votes_log =  Table('wp_gdsr_votes_log', metadata,
    Column(u'record_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'id', MSInteger(display_width=11), primary_key=False),
            Column(u'vote_type', MSString(length=10), primary_key=False),
            Column(u'multi_id', MSInteger(display_width=11), primary_key=False),
            Column(u'user_id', MSInteger(display_width=11), primary_key=False),
            Column(u'vote', MSInteger(display_width=11), primary_key=False),
            Column(u'object', MSText(), primary_key=False, nullable=False),
            Column(u'voted', MSDateTime(timezone=False), primary_key=False),
            Column(u'ip', MSString(length=32), primary_key=False),
            Column(u'user_agent', MSString(length=255), primary_key=False),
            Column(u'comment_id', MSBigInteger(display_width=20), primary_key=False),
    
    
    )
wp_gdsr_votes_trend =  Table('wp_gdsr_votes_trend', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=False),
            Column(u'vote_type', MSString(length=10), primary_key=False),
            Column(u'user_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'user_votes', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_voters', MSInteger(display_width=11), primary_key=False),
            Column(u'visitor_votes', MSInteger(display_width=11), primary_key=False),
            Column(u'vote_date', MSString(length=10), primary_key=False),
    
    
    )
wp_item_category_associations =  Table('wp_item_category_associations', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'category_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'product_id', wp_item_category_associations.c.product_id, wp_item_category_associations.c.category_id, unique=True)
wp_links =  Table('wp_links', metadata,
    Column(u'link_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'link_url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link_name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link_image', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link_target', MSString(length=25), primary_key=False, nullable=False),
            Column(u'link_category', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'link_description', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link_visible', MSString(length=20), primary_key=False, nullable=False),
            Column(u'link_owner', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'link_rating', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'link_updated', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'link_rel', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link_notes', MSMediumText(), primary_key=False, nullable=False),
            Column(u'link_rss', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'link_category', wp_links.c.link_category, unique=False)
Index(u'link_visible', wp_links.c.link_visible, unique=False)
wp_oiopub_affiliates =  Table('wp_oiopub_affiliates', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'level', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'coupon', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'email', MSString(length=128), primary_key=False, nullable=False),
            Column(u'password', MSString(length=32), primary_key=False, nullable=False),
            Column(u'salt', MSString(length=8), primary_key=False, nullable=False),
            Column(u'paypal', MSString(length=64), primary_key=False, nullable=False),
            Column(u'status', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'email', wp_oiopub_affiliates.c.email, unique=False)
Index(u'paypal', wp_oiopub_affiliates.c.paypal, unique=False)
wp_oiopub_affiliates_hits =  Table('wp_oiopub_affiliates_hits', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'ref_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'date', MSDate(), primary_key=False, nullable=False),
            Column(u'ip', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'page', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'ref_id', wp_oiopub_affiliates_hits.c.ref_id, wp_oiopub_affiliates_hits.c.date, unique=False)
wp_oiopub_affiliates_sales =  Table('wp_oiopub_affiliates_sales', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'affiliate_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'affiliate_paid', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'affiliate_amount', MSDecimal(precision=10, scale=2, asdecimal=True), primary_key=False, nullable=False),
            Column(u'affiliate_currency', MSString(length=8), primary_key=False, nullable=False),
            Column(u'purchase_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'purchase_type', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'purchase_time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'purchase_payment', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'affiliate_id', wp_oiopub_affiliates_sales.c.affiliate_id, wp_oiopub_affiliates_sales.c.affiliate_paid, unique=False)
Index(u'purchase_id', wp_oiopub_affiliates_sales.c.purchase_id, unique=False)
wp_oiopub_config =  Table('wp_oiopub_config', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'name', MSString(length=64), primary_key=False, nullable=False),
            Column(u'value', MSLongText(), primary_key=False, nullable=False),
            Column(u'api_load', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'api_load', wp_oiopub_config.c.api_load, unique=False)
wp_oiopub_purchases =  Table('wp_oiopub_purchases', metadata,
    Column(u'item_id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'item_channel', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_type', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_status', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_duration', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_subscription', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_nofollow', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'item_url', MSString(length=255), primary_key=False, nullable=False),
            Column(u'item_tooltip', MSString(length=128), primary_key=False, nullable=False),
            Column(u'item_page', MSString(length=255), primary_key=False, nullable=False),
            Column(u'item_notes', MSText(), primary_key=False, nullable=False),
            Column(u'link_exchange', MSString(length=255), primary_key=False, nullable=False),
            Column(u'post_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'post_author', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'post_phrase', MSString(length=64), primary_key=False, nullable=False),
            Column(u'adv_name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'adv_email', MSString(length=128), primary_key=False, nullable=False),
            Column(u'submit_time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'submit_api', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'payment_txid', MSString(length=32), primary_key=False, nullable=False),
            Column(u'payment_processor', MSString(length=32), primary_key=False, nullable=False),
            Column(u'payment_currency', MSString(length=8), primary_key=False, nullable=False),
            Column(u'payment_amount', MSDecimal(precision=10, scale=2, asdecimal=True), primary_key=False, nullable=False),
            Column(u'payment_time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'payment_next', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'payment_status', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'payment_log', MSText(), primary_key=False, nullable=False),
            Column(u'published_status', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'affiliate_id', MSString(length=16), primary_key=False, nullable=False),
            Column(u'rand_id', MSString(length=64), primary_key=False, nullable=False),
            Column(u'category_id', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'direct_link', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'item_channel', wp_oiopub_purchases.c.item_channel, wp_oiopub_purchases.c.item_status, wp_oiopub_purchases.c.payment_status, unique=False)
Index(u'rand_id', wp_oiopub_purchases.c.rand_id, unique=False)
wp_oiopub_purchases_history =  Table('wp_oiopub_purchases_history', metadata,
    Column(u'ID', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'item', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'processor', MSString(length=16), primary_key=False, nullable=False),
            Column(u'currency', MSString(length=8), primary_key=False, nullable=False),
            Column(u'amount', MSDecimal(precision=10, scale=2, asdecimal=True), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'subscription', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'item', wp_oiopub_purchases_history.c.item, unique=False)
Index(u'time', wp_oiopub_purchases_history.c.time, unique=False)
wp_oiopub_tracker_archive =  Table('wp_oiopub_tracker_archive', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'pid', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'date', MSDate(), primary_key=False, nullable=False),
            Column(u'unique_clicks', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'total_clicks', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'unique_visits', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'total_visits', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'pid', wp_oiopub_tracker_archive.c.pid, unique=False)
Index(u'date', wp_oiopub_tracker_archive.c.date, unique=False)
wp_oiopub_tracker_clicks =  Table('wp_oiopub_tracker_clicks', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'pid', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'date', MSDate(), primary_key=False, nullable=False),
            Column(u'ip', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'agent', MSText(), primary_key=False, nullable=False),
            Column(u'referer', MSText(), primary_key=False, nullable=False),
            Column(u'status', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
wp_oiopub_tracker_visits =  Table('wp_oiopub_tracker_visits', metadata,
    Column(u'id', MSInteger(display_width=10), primary_key=True, nullable=False),
            Column(u'pids', MSText(), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'date', MSDate(), primary_key=False, nullable=False),
            Column(u'ip', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'agent', MSText(), primary_key=False, nullable=False),
            Column(u'referer', MSText(), primary_key=False, nullable=False),
            Column(u'status', MSInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
wp_options =  Table('wp_options', metadata,
    Column(u'option_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'blog_id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'option_name', MSString(length=64), primary_key=True, nullable=False),
            Column(u'option_value', MSLongText(), primary_key=False, nullable=False),
            Column(u'autoload', MSString(length=20), primary_key=False, nullable=False),
    
    
    )
Index(u'option_name', wp_options.c.option_name, unique=False)
wp_postmeta =  Table('wp_postmeta', metadata,
    Column(u'meta_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'post_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'meta_key', MSString(length=255), primary_key=False),
            Column(u'meta_value', MSLongText(), primary_key=False),
    
    
    )
Index(u'post_id', wp_postmeta.c.post_id, unique=False)
Index(u'meta_key', wp_postmeta.c.meta_key, unique=False)
wp_posts =  Table('wp_posts', metadata,
    Column(u'ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'post_author', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'post_date', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'post_date_gmt', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'post_content', MSLongText(), primary_key=False, nullable=False),
            Column(u'post_title', MSText(), primary_key=False, nullable=False),
            Column(u'post_category', MSInteger(display_width=4), primary_key=False, nullable=False),
            Column(u'post_excerpt', MSText(), primary_key=False, nullable=False),
            Column(u'post_status', MSString(length=20), primary_key=False, nullable=False),
            Column(u'comment_status', MSString(length=20), primary_key=False, nullable=False),
            Column(u'ping_status', MSString(length=20), primary_key=False, nullable=False),
            Column(u'post_password', MSString(length=20), primary_key=False, nullable=False),
            Column(u'post_name', MSString(length=200), primary_key=False, nullable=False),
            Column(u'to_ping', MSText(), primary_key=False, nullable=False),
            Column(u'pinged', MSText(), primary_key=False, nullable=False),
            Column(u'post_modified', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'post_modified_gmt', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'post_content_filtered', MSText(), primary_key=False, nullable=False),
            Column(u'post_parent', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'guid', MSString(length=255), primary_key=False, nullable=False),
            Column(u'menu_order', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'post_type', MSString(length=20), primary_key=False, nullable=False),
            Column(u'post_mime_type', MSString(length=100), primary_key=False, nullable=False),
            Column(u'comment_count', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'type_status_date', wp_posts.c.post_type, wp_posts.c.post_status, wp_posts.c.post_date, wp_posts.c.ID, unique=False)
Index(u'yarpp_title', wp_posts.c.post_title, unique=False)
Index(u'post_parent', wp_posts.c.post_parent, unique=False)
Index(u'yarpp_content', wp_posts.c.post_content, unique=False)
Index(u'post_related', wp_posts.c.post_name, wp_posts.c.post_content, unique=False)
Index(u'post_name', wp_posts.c.post_name, unique=False)
wp_product_categories =  Table('wp_product_categories', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'group_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'name', MSText(), primary_key=False, nullable=False),
            Column(u'nice-name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'image', MSText(), primary_key=False),
            Column(u'fee', MSString(length=1), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'category_parent', MSBigInteger(display_width=20), primary_key=False),
            Column(u'order', MSBigInteger(display_width=20), primary_key=False),
            Column(u'display_type', MSString(length=10), primary_key=False),
            Column(u'image_width', MSString(length=32), primary_key=False),
            Column(u'image_height', MSString(length=32), primary_key=False),
    
    
    )
Index(u'group_id', wp_product_categories.c.group_id, unique=False)
Index(u'nice-name', wp_product_categories.c[u'nice-name'], unique=False)
wp_product_files =  Table('wp_product_files', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'filename', MSString(length=255), primary_key=False, nullable=False),
            Column(u'mimetype', MSString(length=128), primary_key=False, nullable=False),
            Column(u'idhash', MSString(length=45), primary_key=False, nullable=False),
            Column(u'preview', MSString(length=255), primary_key=False, nullable=False),
            Column(u'preview_mimetype', MSString(length=128), primary_key=False, nullable=False),
            Column(u'date', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
wp_product_images =  Table('wp_product_images', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'image', MSString(length=255), primary_key=False, nullable=False),
            Column(u'width', MSMediumInteger(display_width=8), primary_key=False, nullable=False),
            Column(u'height', MSMediumInteger(display_width=8), primary_key=False, nullable=False),
            Column(u'image_order', MSString(length=10), primary_key=False, nullable=False),
            Column(u'meta', MSLongText(), primary_key=False),
    
    
    )
Index(u'product_id', wp_product_images.c.product_id, unique=False)
wp_product_list =  Table('wp_product_list', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSText(), primary_key=False, nullable=False),
            Column(u'description', MSLongText(), primary_key=False, nullable=False),
            Column(u'additional_description', MSLongText(), primary_key=False, nullable=False),
            Column(u'price', MSString(length=20), primary_key=False, nullable=False),
            Column(u'weight', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
            Column(u'weight_unit', MSString(length=10), primary_key=False, nullable=False),
            Column(u'pnp', MSString(length=20), primary_key=False, nullable=False),
            Column(u'international_pnp', MSString(length=20), primary_key=False, nullable=False),
            Column(u'file', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'image', MSText(), primary_key=False, nullable=False),
            Column(u'category', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'brand', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'quantity_limited', MSString(length=1), primary_key=False, nullable=False),
            Column(u'quantity', MSInteger(display_width=10), primary_key=False, nullable=False),
            Column(u'special', MSString(length=1), primary_key=False, nullable=False),
            Column(u'special_price', MSString(length=20), primary_key=False, nullable=False),
            Column(u'display_frontpage', MSString(length=1), primary_key=False, nullable=False),
            Column(u'notax', MSString(length=1), primary_key=False, nullable=False),
            Column(u'publish', MSString(length=1), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'donation', MSString(length=1), primary_key=False, nullable=False),
            Column(u'no_shipping', MSString(length=1), primary_key=False, nullable=False),
            Column(u'thumbnail_image', MSText(), primary_key=False),
            Column(u'thumbnail_state', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
wp_product_order =  Table('wp_product_order', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'category_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'order', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'category_id', wp_product_order.c.category_id, wp_product_order.c.product_id, unique=True)
Index(u'order', wp_product_order.c.order, unique=False)
wp_product_rating =  Table('wp_product_rating', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'ipnum', MSString(length=30), primary_key=False, nullable=False),
            Column(u'productid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'rated', MSBoolean(), primary_key=False, nullable=False),
            Column(u'time', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
wp_product_variations =  Table('wp_product_variations', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'variation_association', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'variation_association', wp_product_variations.c.variation_association, unique=False)
wp_purchase_logs =  Table('wp_purchase_logs', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'totalprice', MSString(length=128), primary_key=False, nullable=False),
            Column(u'statusno', MSSmallInteger(display_width=6), primary_key=False, nullable=False),
            Column(u'sessionid', MSString(length=255), primary_key=False, nullable=False),
            Column(u'transactid', MSString(length=255), primary_key=False, nullable=False),
            Column(u'authcode', MSString(length=255), primary_key=False, nullable=False),
            Column(u'downloadid', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'processed', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'user_ID', MSBigInteger(display_width=20), primary_key=False),
            Column(u'date', MSString(length=255), primary_key=False, nullable=False),
            Column(u'gateway', MSString(length=64), primary_key=False, nullable=False),
            Column(u'billing_country', MSChar(length=6), primary_key=False, nullable=False),
            Column(u'shipping_country', MSChar(length=6), primary_key=False, nullable=False),
            Column(u'base_shipping', MSString(length=128), primary_key=False, nullable=False),
            Column(u'email_sent', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'stock_adjusted', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'discount_value', MSString(length=32), primary_key=False, nullable=False),
            Column(u'discount_data', MSText(), primary_key=False, nullable=False),
            Column(u'track_id', MSString(length=50), primary_key=False),
            Column(u'shipping_region', MSChar(length=6), primary_key=False, nullable=False),
            Column(u'find_us', MSString(length=255), primary_key=False, nullable=False),
            Column(u'engravetext', MSString(length=255), primary_key=False),
            Column(u'closest_store', MSString(length=255), primary_key=False),
            Column(u'google_order_number', MSString(length=20), primary_key=False, nullable=False),
            Column(u'google_user_marketing_preference', MSString(length=10), primary_key=False, nullable=False),
            Column(u'google_status', MSLongText(), primary_key=False, nullable=False),
            Column(u'shipping_method', MSString(length=64), primary_key=False),
            Column(u'shipping_option', MSString(length=128), primary_key=False),
            Column(u'affiliate_id', MSString(length=32), primary_key=False),
    
    
    )
Index(u'sessionid', wp_purchase_logs.c.sessionid, unique=True)
Index(u'gateway', wp_purchase_logs.c.gateway, unique=False)
wp_purchase_statuses =  Table('wp_purchase_statuses', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'colour', MSString(length=6), primary_key=False, nullable=False),
    
    
    )
wp_region_tax =  Table('wp_region_tax', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'country_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'name', MSString(length=64), primary_key=False, nullable=False),
            Column(u'code', MSChar(length=2), primary_key=False, nullable=False),
            Column(u'tax', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
    
    
    )
Index(u'country_id', wp_region_tax.c.country_id, unique=False)
wp_submited_form_data =  Table('wp_submited_form_data', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'log_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'form_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'value', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
Index(u'log_id', wp_submited_form_data.c.log_id, wp_submited_form_data.c.form_id, unique=False)
wp_term_relationships =  Table('wp_term_relationships', metadata,
    Column(u'object_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'term_taxonomy_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'term_order', MSInteger(display_width=11), primary_key=False, nullable=False),
    
    
    )
Index(u'term_taxonomy_id', wp_term_relationships.c.term_taxonomy_id, unique=False)
wp_term_taxonomy =  Table('wp_term_taxonomy', metadata,
    Column(u'term_taxonomy_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'term_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'taxonomy', MSString(length=32), primary_key=False, nullable=False),
            Column(u'description', MSLongText(), primary_key=False, nullable=False),
            Column(u'parent', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'count', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'term_id_taxonomy', wp_term_taxonomy.c.term_id, wp_term_taxonomy.c.taxonomy, unique=True)
Index(u'taxonomy', wp_term_taxonomy.c.taxonomy, unique=False)
wp_terms =  Table('wp_terms', metadata,
    Column(u'term_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=200), primary_key=False, nullable=False),
            Column(u'slug', MSString(length=200), primary_key=False, nullable=False),
            Column(u'term_group', MSBigInteger(display_width=10), primary_key=False, nullable=False),
    
    
    )
Index(u'slug', wp_terms.c.slug, unique=True)
Index(u'name', wp_terms.c.name, unique=False)
wp_usermeta =  Table('wp_usermeta', metadata,
    Column(u'umeta_id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'user_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'meta_key', MSString(length=255), primary_key=False),
            Column(u'meta_value', MSLongText(), primary_key=False),
    
    
    )
Index(u'user_id', wp_usermeta.c.user_id, unique=False)
Index(u'meta_key', wp_usermeta.c.meta_key, unique=False)
wp_users =  Table('wp_users', metadata,
    Column(u'ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'user_login', MSString(length=60), primary_key=False, nullable=False),
            Column(u'user_pass', MSString(length=64), primary_key=False, nullable=False),
            Column(u'user_nicename', MSString(length=50), primary_key=False, nullable=False),
            Column(u'user_email', MSString(length=100), primary_key=False, nullable=False),
            Column(u'user_url', MSString(length=100), primary_key=False, nullable=False),
            Column(u'user_registered', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'user_activation_key', MSString(length=60), primary_key=False, nullable=False),
            Column(u'user_status', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'display_name', MSString(length=250), primary_key=False, nullable=False),
    
    
    )
Index(u'user_login_key', wp_users.c.user_login, unique=False)
Index(u'user_nicename', wp_users.c.user_nicename, unique=False)
wp_variation_associations =  Table('wp_variation_associations', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'type', MSString(length=64), primary_key=False, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'associated_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'variation_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'associated_id', wp_variation_associations.c.associated_id, unique=False)
Index(u'variation_id', wp_variation_associations.c.variation_id, unique=False)
wp_variation_priceandstock =  Table('wp_variation_priceandstock', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'stock', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'price', MSString(length=32), primary_key=False, nullable=False),
            Column(u'weight', MSString(length=64), primary_key=False),
            Column(u'weight_unit', MSString(length=10), primary_key=False, nullable=False),
            Column(u'visibility', MSString(length=1), primary_key=False, nullable=False),
            Column(u'file', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'product_id', wp_variation_priceandstock.c.product_id, unique=False)
wp_variation_values =  Table('wp_variation_values', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=128), primary_key=False, nullable=False),
            Column(u'variation_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'variation_id', wp_variation_values.c.variation_id, unique=False)
wp_variation_values_associations =  Table('wp_variation_values_associations', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'value_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'visible', MSString(length=1), primary_key=False, nullable=False),
            Column(u'variation_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
    
    
    )
Index(u'product_id', wp_variation_values_associations.c.product_id, wp_variation_values_associations.c.value_id, wp_variation_values_associations.c.variation_id, unique=False)
wp_wpppd_donations =  Table('wp_wpppd_donations', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'date', MSInteger(display_width=11), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'currency', MSString(length=25), primary_key=False, nullable=False),
            Column(u'amount', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
            Column(u'email', MSString(length=255), primary_key=False, nullable=False),
            Column(u'link', MSString(length=255), primary_key=False, nullable=False),
            Column(u'display', MSString(length=255), primary_key=False, nullable=False),
    
    
    )
wp_wpsc_categorisation_groups =  Table('wp_wpsc_categorisation_groups', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False, nullable=False),
            Column(u'description', MSText(), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
            Column(u'default', MSString(length=1), primary_key=False, nullable=False),
    
    
    )
Index(u'group_name', wp_wpsc_categorisation_groups.c.name, unique=False)
wp_wpsc_coupon_codes =  Table('wp_wpsc_coupon_codes', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'coupon_code', MSString(length=255), primary_key=False),
            Column(u'value', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'is-percentage', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'use-once', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'is-used', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'active', MSChar(length=1), primary_key=False, nullable=False),
            Column(u'every_product', MSString(length=255), primary_key=False, nullable=False),
            Column(u'start', MSDateTime(timezone=False), primary_key=False, nullable=False),
            Column(u'expiry', MSDateTime(timezone=False), primary_key=False, nullable=False),
    
    
    )
Index(u'coupon_code', wp_wpsc_coupon_codes.c.coupon_code, unique=False)
Index(u'active', wp_wpsc_coupon_codes.c.active, unique=False)
Index(u'start', wp_wpsc_coupon_codes.c.start, unique=False)
Index(u'expiry', wp_wpsc_coupon_codes.c.expiry, unique=False)
wp_wpsc_logged_subscriptions =  Table('wp_wpsc_logged_subscriptions', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'cart_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'user_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'length', MSString(length=64), primary_key=False, nullable=False),
            Column(u'start_time', MSString(length=64), primary_key=False, nullable=False),
            Column(u'active', MSString(length=1), primary_key=False, nullable=False),
    
    
    )
Index(u'cart_id', wp_wpsc_logged_subscriptions.c.cart_id, unique=False)
Index(u'user_id', wp_wpsc_logged_subscriptions.c.user_id, unique=False)
Index(u'start_time', wp_wpsc_logged_subscriptions.c.start_time, unique=False)
wp_wpsc_productmeta =  Table('wp_wpsc_productmeta', metadata,
    Column(u'id', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'meta_key', MSString(length=255), primary_key=False),
            Column(u'meta_value', MSLongText(), primary_key=False),
            Column(u'custom', MSString(length=1), primary_key=False, nullable=False),
    
    
    )
Index(u'product_id', wp_wpsc_productmeta.c.product_id, unique=False)
Index(u'meta_key', wp_wpsc_productmeta.c.meta_key, unique=False)
Index(u'custom', wp_wpsc_productmeta.c.custom, unique=False)
wp_wpsc_variation_combinations =  Table('wp_wpsc_variation_combinations', metadata,
    Column(u'product_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'priceandstock_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'value_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'variation_id', MSBigInteger(display_width=20), primary_key=False, nullable=False),
            Column(u'all_variation_ids', MSString(length=64), primary_key=False, nullable=False),
    
    
    )
Index(u'product_id', wp_wpsc_variation_combinations.c.product_id, unique=False)
Index(u'priceandstock_id', wp_wpsc_variation_combinations.c.priceandstock_id, unique=False)
Index(u'all_variation_ids', wp_wpsc_variation_combinations.c.all_variation_ids, unique=False)
Index(u'value_id', wp_wpsc_variation_combinations.c.value_id, unique=False)
Index(u'variation_id', wp_wpsc_variation_combinations.c.variation_id, unique=False)
wp_yarpp_keyword_cache =  Table('wp_yarpp_keyword_cache', metadata,
    Column(u'ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'body', MSText(), primary_key=False),
            Column(u'title', MSText(), primary_key=False),
            Column(u'date', MSTimeStamp(timezone=False), primary_key=False, nullable=False),
    
    
    )
wp_yarpp_related_cache =  Table('wp_yarpp_related_cache', metadata,
    Column(u'reference_ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'ID', MSBigInteger(display_width=20), primary_key=True, nullable=False),
            Column(u'score', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False, nullable=False),
            Column(u'date', MSTimeStamp(timezone=False), primary_key=False, nullable=False),
    
    
    )
