# property type list

PROPERTY_TYPE_NORMAL = "Normal"
PROPERTY_TYPE_CATEGORY = "Category"
PROPERTY_TYPE_CATEGORY_MEMBER = "Category Member"
PROPERTY_TYPE_PARENT = "Parent"
PROPERTY_TYPE_CHILD = "Child"


# ptl - property datatype list

PROPERTY_DATATYPE_NOPROP = "None"
PROPERTY_DATATYPE_CATEGORY = "Category"
PROPERTY_DATATYPE_PARENT = "Parent"
PROPERTY_DATATYPE_NUMERIC = "Numeric"   # Non-standard
PROPERTY_DATATYPE_TEXT = "Text"   # Non-standard
PROPERTY_DATATYPE_LOGICAL = "Logical"   # Non-standard
PROPERTY_DATATYPE_DATE = "Date"
PROPERTY_DATATYPE_TIME = "Time"   # Non-standard
PROPERTY_DATATYPE_DATETIME = "Date/Time"   # Non-standard
PROPERTY_DATATYPE_STRING = "String"
PROPERTY_DATATYPE_INTEGER = "Integer"
PROPERTY_DATATYPE_UINTEGER = "Unsigned Integer"
PROPERTY_DATATYPE_FLOAT = "Float"
PROPERTY_DATATYPE_BOOLEAN = "Boolean"
PROPERTY_DATATYPE_FONT = "Font"
PROPERTY_DATATYPE_FONTDATA = "Font Data"
PROPERTY_DATATYPE_COLOUR = "Colour"
PROPERTY_DATATYPE_SYSTEMCOLOUR = "System Colour"
PROPERTY_DATATYPE_FLAGS = "Flags"
PROPERTY_DATATYPE_CURSOR = "Cursor"
PROPERTY_DATATYPE_SIZE = "Size"
PROPERTY_DATATYPE_POINT = "Position"
PROPERTY_DATATYPE_DIR = "Dir"
PROPERTY_DATATYPE_DIRS = "Dirs"
PROPERTY_DATATYPE_LONGSTRING = "Long String"
PROPERTY_DATATYPE_ADVIMAGEFILE = "Advanced Image File"
PROPERTY_DATATYPE_CUSTOM = "Custom User Property"
PROPERTY_DATATYPE_IMAGEFILE = "Image File"
PROPERTY_DATATYPE_ENUM = "Enumeration"
PROPERTY_DATATYPE_EDITENUM = "Edit Enumeration"
PROPERTY_DATATYPE_MULTICHOICE = "MultiChoice"
PROPERTY_DATATYPE_ARRAYSTRING = "Array String"
PROPERTY_DATATYPE_ARRAYDOUBLE = "Array Double"
PROPERTY_DATATYPE_FILE = "File"

LIST_PROPERTY_DATATYPE = []
# LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_NOPROP )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_NUMERIC )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_FLOAT )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_INTEGER )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_UINTEGER )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_TEXT )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_STRING )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_LOGICAL )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_BOOLEAN )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_DATE )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_TIME )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_DATETIME )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_FONT )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_COLOUR )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_SYSTEMCOLOUR )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_FLAGS )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_CURSOR )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_SIZE )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_POINT )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_FONTDATA )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_DIR )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_DIRS )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_LONGSTRING )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_ADVIMAGEFILE )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_CUSTOM )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_IMAGEFILE )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_ENUM )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_EDITENUM )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_MULTICHOICE )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_ARRAYSTRING )
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_ARRAYDOUBLE)
LIST_PROPERTY_DATATYPE.append( PROPERTY_DATATYPE_FILE )

