# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


app_setting =  Table('app_setting', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'value', MSString(length=255), primary_key=False),
            Column(u'description', MSText(), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'field_type', MSString(length=255), primary_key=False),
    
    
    )


article =  Table('article', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False),
            Column(u'body', MSText(), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )


case_columns_setting =  Table('case_columns_setting', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sfcontact_setting_id', MSInteger(display_width=11), primary_key=False),
            Column(u'your_component__c', MSBoolean(), primary_key=False),
            Column(u'your_sfuser___last_name', MSBoolean(), primary_key=False),
            Column(u'your_sf_type', MSBoolean(), primary_key=False),
            Column(u'your_customer_priority__c', MSBoolean(), primary_key=False),
            Column(u'your_sfcase___created_date', MSBoolean(), primary_key=False),
            Column(u'your_sfcase___last_updated__c', MSBoolean(), primary_key=False),
            Column(u'your_sfcontact___last_name', MSBoolean(), primary_key=False),
            Column(u'your_expected_resolution_date__c', MSBoolean(), primary_key=False),
            Column(u'all_component__c', MSBoolean(), primary_key=False),
            Column(u'all_sfuser___last_name', MSBoolean(), primary_key=False),
            Column(u'all_sf_type', MSBoolean(), primary_key=False),
            Column(u'all_customer_priority__c', MSBoolean(), primary_key=False),
            Column(u'all_sfcase___created_date', MSBoolean(), primary_key=False),
            Column(u'all_sfcase___last_updated__c', MSBoolean(), primary_key=False),
            Column(u'all_sfcontact___last_name', MSBoolean(), primary_key=False),
            Column(u'all_expected_resolution_date__c', MSBoolean(), primary_key=False),
            Column(u'your_cr_status__c', MSBoolean(), primary_key=False),
            Column(u'all_cr_status__c', MSBoolean(), primary_key=False),
            Column(u'your_expedited_priority__c', MSBoolean(), primary_key=False),
            Column(u'your_contact_id', MSBoolean(), primary_key=False),
            Column(u'your_customer_tracking__c', MSBoolean(), primary_key=False),
            Column(u'your_weekly_notes__c', MSBoolean(), primary_key=False),
            Column(u'all_expedited_priority__c', MSBoolean(), primary_key=False),
            Column(u'all_contact_id', MSBoolean(), primary_key=False),
            Column(u'all_customer_tracking__c', MSBoolean(), primary_key=False),
            Column(u'all_weekly_notes__c', MSBoolean(), primary_key=False),
            Column(u'your_tag__c', MSBoolean(), primary_key=False),
            Column(u'all_tag__c', MSBoolean(), primary_key=False),
            Column(u'your_cr_number__c', MSBoolean(), primary_key=False),
            Column(u'all_cr_number__c', MSBoolean(), primary_key=False),
            Column(u'your_account', MSBoolean(), primary_key=False),
            Column(u'all_account', MSBoolean(), primary_key=False),
            Column(u'all_expected_build_date__c', MSBoolean(), primary_key=False),
            Column(u'your_expected_build_date__c', MSBoolean(), primary_key=False),
    
    
    )


case_report =  Table('case_report', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'contact_id', MSString(length=255), primary_key=False),
            Column(u'query', MSString(length=255), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'shared', MSBoolean(), primary_key=False),
            Column(u'columns', MSString(length=255), primary_key=False),
            Column(u'account_id', MSString(length=255), primary_key=False),
            Column(u'status_array', MSText(), primary_key=False),
            Column(u'column_array', MSText(), primary_key=False),
            Column(u'account_ids_array', MSText(), primary_key=False),
    
    
    )


case_view_setting =  Table('case_view_setting', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sfcontact_setting_id', MSString(length=255), primary_key=False),
            Column(u'status', MSText(), primary_key=False),
            Column(u'viewable', MSBoolean(), primary_key=False),
    
    
    )


country =  Table('country', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )


error =  Table('error', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'sf_entity', MSString(length=255), primary_key=False),
            Column(u'sql_entity', MSString(length=255), primary_key=False),
            Column(u'error_message', MSLongText(), primary_key=False),
            Column(u'created_time', MSDateTime(timezone=False), primary_key=False),
            Column(u'other_information', MSLongText(), primary_key=False),
            Column(u'last_modified', MSDateTime(timezone=False), primary_key=False),
    
    
    )


page =  Table('page', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'controller', MSString(length=255), primary_key=False),
            Column(u'action', MSString(length=255), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )


rails_cron =  Table('rails_cron', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'command', MSText(), primary_key=False),
            Column(u'start', MSInteger(display_width=11), primary_key=False),
            Column(u'finish', MSInteger(display_width=11), primary_key=False),
            Column(u'every', MSInteger(display_width=11), primary_key=False),
            Column(u'concurrent', MSBoolean(), primary_key=False),
            Column(u'interval_string', MSString(length=255), primary_key=False),
    
    
    )


rating =  Table('rating', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'one', MSInteger(display_width=11), primary_key=False),
            Column(u'two', MSInteger(display_width=11), primary_key=False),
            Column(u'three', MSInteger(display_width=11), primary_key=False),
            Column(u'four', MSInteger(display_width=11), primary_key=False),
            Column(u'sfsolution_id', MSString(length=255), primary_key=False),
    
    
    )


refresh_cache =  Table('refresh_cache', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'refreshable_type', MSString(length=255), primary_key=False),
            Column(u'refreshable_id', MSString(length=255), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )


schema_info =  Table('schema_info', metadata,
    Column(u'version', MSInteger(display_width=11), primary_key=False),
    
    
    )


sfaccount =  Table('sfaccount', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'sf_type', MSString(length=255), primary_key=False),
            Column(u'parent_id', MSString(length=255), primary_key=False),
            Column(u'billing_street', MSString(length=255), primary_key=False),
            Column(u'billing_city', MSString(length=255), primary_key=False),
            Column(u'billing_state', MSString(length=255), primary_key=False),
            Column(u'billing_postal_code', MSString(length=255), primary_key=False),
            Column(u'billing_country', MSString(length=255), primary_key=False),
            Column(u'shipping_street', MSString(length=255), primary_key=False),
            Column(u'shipping_city', MSString(length=255), primary_key=False),
            Column(u'shipping_state', MSString(length=255), primary_key=False),
            Column(u'shipping_postal_code', MSString(length=255), primary_key=False),
            Column(u'shipping_country', MSString(length=255), primary_key=False),
            Column(u'phone', MSString(length=255), primary_key=False),
            Column(u'fax', MSString(length=255), primary_key=False),
            Column(u'website', MSString(length=255), primary_key=False),
            Column(u'description', MSLongText(), primary_key=False),
            Column(u'site', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'host_id__c', MSString(length=255), primary_key=False),
            Column(u'sales_region__c', MSString(length=255), primary_key=False),
            Column(u'dun_snumber__c', MSString(length=255), primary_key=False),
            Column(u'tam_front_end_seats__c', MSString(length=255), primary_key=False),
            Column(u'tam_back_end_seats__c', MSString(length=255), primary_key=False),
            Column(u'customer_id__c', MSString(length=255), primary_key=False),
            Column(u'address_issue__c', MSString(length=255), primary_key=False),
            Column(u'credit_rating__c', MSString(length=255), primary_key=False),
            Column(u'nda__c', MSString(length=255), primary_key=False),
            Column(u'nda_description__c', MSString(length=255), primary_key=False),
            Column(u'customer_support_alias__c', MSString(length=255), primary_key=False),
            Column(u'sap_sync_status__c', MSString(length=255), primary_key=False),
            Column(u'sap_payment_terms__c', MSString(length=255), primary_key=False),
            Column(u'sap_account_group__c', MSString(length=255), primary_key=False),
            Column(u'lead_ae_email__c', MSString(length=255), primary_key=False),
            Column(u'sap_sales_districts__c', MSString(length=255), primary_key=False),
            Column(u'sap_customer_id__c', MSString(length=255), primary_key=False),
            Column(u'tsmc_lib_nda_front_end__c', MSString(length=255), primary_key=False),
            Column(u'sap_legacy_id__c', MSString(length=255), primary_key=False),
            Column(u'sla__c', MSString(length=255), primary_key=False),
            Column(u'initial_sap_upload__c', MSString(length=255), primary_key=False),
            Column(u'nda_expiration_date__c', MSDate(), primary_key=False),
            Column(u'tsmc_lib_nda_complete__c', MSString(length=255), primary_key=False),
            Column(u'credit_score__c', MSString(length=255), primary_key=False),
            Column(u'entity_type__c', MSString(length=255), primary_key=False),
            Column(u'credit_score_updated__c', MSDate(), primary_key=False),
            Column(u'activities__c', MSLongText(), primary_key=False),
            Column(u'dns_domain__c', MSString(length=255), primary_key=False),
            Column(u'allow_molten__c', MSString(length=255), primary_key=False),
            Column(u'toll_free_phone__c', MSString(length=255), primary_key=False),
            Column(u'account_type_code__c', MSString(length=255), primary_key=False),
            Column(u'sap_org_id__c', MSString(length=255), primary_key=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'type', MSString(length=255), primary_key=False),
            Column(u'sap_log_id__c', MSString(length=255), primary_key=False),
            Column(u'vat__c', MSString(length=255), primary_key=False),
            Column(u'sap_shipping_account_id__c', MSString(length=255), primary_key=False),
            Column(u'email_flyer__c', MSString(length=255), primary_key=False),
            Column(u'last_activity_date', MSString(length=255), primary_key=False),
            Column(u'sap_customer_tax_group__c', MSString(length=255), primary_key=False),
            Column(u'portal_default_type__c', MSString(length=255), primary_key=False),
            Column(u'portal_case_types__c', MSString(length=255), primary_key=False),
            Column(u'portal_case_scope__c', MSString(length=255), primary_key=False),
            Column(u'industry', MSString(length=255), primary_key=False),
            Column(u'annual_revenue', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
            Column(u'master_record_id', MSString(length=255), primary_key=False),
    )
Index(u'sfaccount_sf_id_idx', sfaccount.c.sf_id, unique=True)
Index(u'index_sfaccount_on_sf_id', sfaccount.c.sf_id, unique=False)


sfattach =  Table('sfattach', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'name', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'is_private', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'content_type', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'body_length', MSInteger(display_width=11), primary_key=False),
            Column(u'body', MSLongText(charset=u'latin1'), primary_key=False),
            Column(u'owner_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'sf_id', MSString(length=255, charset=u'latin1'), primary_key=False, nullable=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfattach_sf_id_idx', sfattach.c.sf_id, unique=True)
Index(u'index_sfattach_on_parent_id', sfattach.c.parent_id, unique=False)


sfcase =  Table('sfcase', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'case_number', MSInteger(display_width=11), primary_key=False),
            Column(u'contact_id', MSString(length=255), primary_key=False),
            Column(u'asset_id', MSString(length=255), primary_key=False),
            Column(u'supplied_name', MSString(length=255), primary_key=False),
            Column(u'supplied_email', MSString(length=255), primary_key=False),
            Column(u'supplied_phone', MSString(length=255), primary_key=False),
            Column(u'supplied_company', MSString(length=255), primary_key=False),
            Column(u'sf_type', MSString(length=255), primary_key=False),
            Column(u'record_type_id', MSString(length=255), primary_key=False),
            Column(u'status', MSString(length=255), primary_key=False),
            Column(u'origin', MSString(length=255), primary_key=False),
            Column(u'is_visible_in_self_service', MSString(length=255), primary_key=False),
            Column(u'subject', MSString(length=255), primary_key=False),
            Column(u'priority', MSString(length=255), primary_key=False),
            Column(u'description', MSLongText(), primary_key=False),
            Column(u'is_closed', MSString(length=255), primary_key=False),
            Column(u'closed_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'is_escalated', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'quart_formal__c', MSString(length=255), primary_key=False),
            Column(u'clarify_id__c', MSString(length=255), primary_key=False),
            Column(u'originator__c', MSString(length=255), primary_key=False),
            Column(u'customer_priority__c', MSString(length=255), primary_key=False),
            Column(u'operating_system__c', MSString(length=255), primary_key=False),
            Column(u'reproducible__c', MSString(length=255), primary_key=False),
            Column(u'component__c', MSString(length=255), primary_key=False),
            Column(u'customer_tracking__c', MSString(length=255), primary_key=False),
            Column(u'query_build_view__c', MSString(length=255), primary_key=False),
            Column(u'dataor_test_case_provided__c', MSString(length=255), primary_key=False),
            Column(u'design_geometryn_m__c', MSString(length=255), primary_key=False),
            Column(u'foundry__c', MSString(length=255), primary_key=False),
            Column(u'cell_count_k_objects__c', MSString(length=255), primary_key=False),
            Column(u'speed_m_hz__c', MSString(length=255), primary_key=False),
            Column(u'scopeof_flow__c', MSString(length=255), primary_key=False),
            Column(u'formal_verification__c', MSString(length=255), primary_key=False),
            Column(u'qualityof_results__c', MSString(length=255), primary_key=False),
            Column(u'hdl__c', MSString(length=255), primary_key=False),
            Column(u'test_case_path__c', MSString(length=255), primary_key=False),
            Column(u'std_cell_library__c', MSString(length=255), primary_key=False),
            Column(u'tape_out_date__c', MSDate(), primary_key=False),
            Column(u'synthesis_tool__c', MSString(length=255), primary_key=False),
            Column(u'schedule_status__c', MSString(length=255), primary_key=False),
            Column(u'time_stamp_build__c', MSString(length=255), primary_key=False),
            Column(u'version_number__c', MSString(length=255), primary_key=False),
            Column(u'noise_signoff__c', MSString(length=255), primary_key=False),
            Column(u'power_signoff__c', MSString(length=255), primary_key=False),
            Column(u'clarify_customer__c', MSString(length=255), primary_key=False),
            Column(u'analysis_tool__c', MSString(length=255), primary_key=False),
            Column(u'target_release__c', MSString(length=255), primary_key=False),
            Column(u'clarify_create_date__c', MSDate(), primary_key=False),
            Column(u'program_area__c', MSString(length=255), primary_key=False),
            Column(u'expedited_priority__c', MSString(length=255), primary_key=False),
            Column(u'target_fast_track_build__c', MSDate(), primary_key=False),
            Column(u'estimated_start_date__c', MSDate(), primary_key=False),
            Column(u'estimated_finish_date__c', MSDate(), primary_key=False),
            Column(u'test_case_provided__c', MSString(length=255), primary_key=False),
            Column(u'customer_visible__c', MSString(length=255), primary_key=False),
            Column(u'opportunity_name__c', MSString(length=255), primary_key=False),
            Column(u'requested_start_date__c', MSDate(), primary_key=False),
            Column(u'requested_end_date__c', MSDate(), primary_key=False),
            Column(u'initial_quality_of_results__c', MSString(length=255), primary_key=False),
            Column(u'initial_util__c', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False),
            Column(u'palace_options_used__c', MSString(length=255), primary_key=False),
            Column(u'initial_speed__c', MSString(length=255), primary_key=False),
            Column(u'design_top_level_name__c', MSString(length=255), primary_key=False),
            Column(u'mode__c', MSString(length=255), primary_key=False),
            Column(u'number_of_clocks__c', MSString(length=255), primary_key=False),
            Column(u'number_of_design_blocks__c', MSString(length=255), primary_key=False),
            Column(u'power_analysis_tool__c', MSString(length=255), primary_key=False),
            Column(u'tape_out_limiting__c', MSString(length=255), primary_key=False),
            Column(u'sales_opportunity_related__c', MSString(length=255), primary_key=False),
            Column(u'benmark_impacted__c', MSString(length=255), primary_key=False),
            Column(u'special_situation__c', MSString(length=255), primary_key=False),
            Column(u'special_situation_desc__c', MSString(length=255), primary_key=False),
            Column(u'benchmark_case__c', MSString(length=255), primary_key=False),
            Column(u'product__c', MSString(length=255), primary_key=False),
            Column(u'is_closeable__c', MSString(length=255), primary_key=False),
            Column(u'schedule_comments__c', MSString(length=255), primary_key=False),
            Column(u'shadow_status__c', MSString(length=255), primary_key=False),
            Column(u'code_streams_priority__c', MSString(length=255), primary_key=False),
            Column(u'tag__c', MSString(length=255), primary_key=False),
            Column(u'engineer_assigned__c', MSString(length=255), primary_key=False),
            Column(u'logic_verification__c', MSString(length=255), primary_key=False),
            Column(u'physical_verification__c', MSString(length=255), primary_key=False),
            Column(u'extraction__c', MSString(length=255), primary_key=False),
            Column(u'timing_signoff__c', MSString(length=255), primary_key=False),
            Column(u'dft__c', MSString(length=255), primary_key=False),
            Column(u'expected_build_date__c', MSDate(), primary_key=False),
            Column(u'man_hours_of_effort__c', MSString(length=255), primary_key=False),
            Column(u'workaround_description__c', MSString(length=255), primary_key=False),
            Column(u'workaround_available__c', MSString(length=255), primary_key=False),
            Column(u'needs_docs__c', MSString(length=255), primary_key=False),
            Column(u'target_releases__c', MSString(length=255), primary_key=False),
            Column(u'expected_resolution_date__c', MSDate(), primary_key=False),
            Column(u'fix_version__c', MSString(length=255), primary_key=False),
            Column(u'cr_list_id__c', MSString(length=255), primary_key=False),
            Column(u'crash_details__c', MSString(length=255), primary_key=False),
            Column(u'description_notes__c', MSString(length=255), primary_key=False),
            Column(u'tech_campaign_id__c', MSString(length=255), primary_key=False),
            Column(u'release_note__c', MSString(length=255), primary_key=False),
            Column(u'tech_campaign2_id__c', MSString(length=255), primary_key=False),
            Column(u'r_d_submission__c', MSString(length=255), primary_key=False),
            Column(u'pe_owner_user_id__c', MSString(length=255), primary_key=False),
            Column(u'component_link_id__c', MSString(length=255), primary_key=False),
            Column(u'aging_weeks__c', MSString(length=255), primary_key=False),
            Column(u'internal_comments__c', MSString(length=255), primary_key=False),
            Column(u'committed__c', MSString(length=255), primary_key=False),
            Column(u'level_of_effort__c', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'type', MSString(length=255), primary_key=False),
            Column(u'sql_sync_id__c', MSString(length=255), primary_key=False),
            Column(u'pe_checkpoint_id__c', MSString(length=255), primary_key=False),
            Column(u'status_1_stream__c', MSString(length=255), primary_key=False),
            Column(u'status_2_stream__c', MSString(length=255), primary_key=False),
            Column(u'status_3_stream__c', MSString(length=255), primary_key=False),
            Column(u'x1st_stream__c', MSString(length=255), primary_key=False),
            Column(u'x2nd_stream__c', MSString(length=255), primary_key=False),
            Column(u'x3rd_stream__c', MSString(length=255), primary_key=False),
            Column(u'weekly_notes__c', MSText(), primary_key=False),
            Column(u'tech_campaign_task_id__c', MSString(length=255), primary_key=False),
            Column(u'due_date__c', MSString(length=255), primary_key=False),
            Column(u'has_comments_unread_by_owner', MSString(length=255), primary_key=False),
            Column(u'has_css_comments', MSString(length=255), primary_key=False),
            Column(u'fast_track_required__c', MSString(length=255), primary_key=False),
            Column(u'target_analysis_done__c', MSString(length=255), primary_key=False),
            Column(u'target_fix_available__c', MSString(length=255), primary_key=False),
            Column(u'target_fix_merged__c', MSString(length=255), primary_key=False),
            Column(u'actual_analysis_done__c', MSString(length=255), primary_key=False),
            Column(u'actual_fix_available__c', MSString(length=255), primary_key=False),
            Column(u'actual_fix_merged__c', MSString(length=255), primary_key=False),
            Column(u'actual_fix_to_scm__c', MSString(length=255), primary_key=False),
            Column(u'target_fix_stream__c', MSString(length=255), primary_key=False),
            Column(u'cr_status__c', MSString(length=255), primary_key=False),
            Column(u'customer_account_id__c', MSString(length=255), primary_key=False),
            Column(u'related_documentation_completed__c', MSString(length=255), primary_key=False),
            Column(u'reason_for_urgent_and_critical_priority__c', MSString(length=255), primary_key=False),
            Column(u'committed_finish_date__c', MSString(length=255), primary_key=False),
            Column(u'delta_commit_to_actual__c', MSString(length=255), primary_key=False),
            Column(u'committed_fix_date__c', MSString(length=255), primary_key=False),
            Column(u'delta_expected_to_commit__c', MSString(length=255), primary_key=False),
            Column(u'r_d_first_owner__c', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'first_support_owner__c', MSString(length=255), primary_key=False),
            Column(u'reason', MSString(length=255), primary_key=False),
            Column(u'account_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
            Column(u'has_self_service_comments', MSString(length=255), primary_key=False),
            Column(u'parent_id', MSString(length=255), primary_key=False),
            Column(u'r_d_owner_id__c', MSString(length=255), primary_key=False),
            Column(u'branch_name__c', MSString(length=255), primary_key=False),
            Column(u'estimated_effort__c', MSString(length=255), primary_key=False),
            Column(u'internal_release_number__c', MSString(length=255), primary_key=False),
            Column(u'external_release_number__c', MSString(length=255), primary_key=False),
            Column(u'other__c', MSString(length=255), primary_key=False),
            Column(u'fixed_version__c', MSString(length=255), primary_key=False),
            Column(u'last_updated__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'critical_date__c', MSString(length=255), primary_key=False),
            Column(u'latest_scm_or_ft_build_tested_against__c', MSString(length=255), primary_key=False),
            Column(u'last_modified_age__c', MSString(length=255), primary_key=False),
            Column(u'task_force__c', MSString(length=255), primary_key=False),
            Column(u'cr_number__c', MSString(length=255), primary_key=False),
            Column(u'parent_case_id__c', MSString(length=255), primary_key=False),
            Column(u'release_notes_documentation__c', MSString(length=255), primary_key=False),
            Column(u'unit_system_test_details__c', MSString(length=255), primary_key=False),
            Column(u'tech_pubs_completed__c', MSString(length=255), primary_key=False),
            Column(u'cc__c', MSString(length=255), primary_key=False),
            Column(u'marketing_input__c', MSString(length=255), primary_key=False),
            Column(u'tf_status__c', MSString(length=255), primary_key=False),
            Column(u'tf_resolved__c', MSString(length=255), primary_key=False),
            Column(u'tf_grouping_text__c', MSString(length=255), primary_key=False),
            Column(u'expected_specification_date__c', MSString(length=255), primary_key=False),
            Column(u'r_d_commitment_date__c', MSString(length=255), primary_key=False),
            Column(u'requested_fix_stream__c', MSString(length=255), primary_key=False),
            Column(u'requested_fix_stream_del__c', MSString(length=255), primary_key=False),
            Column(u'updated_field_data__c', MSString(length=255), primary_key=False),
            Column(u'site__c', MSString(length=255), primary_key=False),
            Column(u'url__c', MSString(length=255), primary_key=False),
            Column(u'golivedate__c', MSString(length=255), primary_key=False),
            Column(u'file_uploaded__c', MSString(length=255), primary_key=False),
            Column(u'go_live_date__c', MSString(length=255), primary_key=False),
            Column(u'manager_s_name__c', MSString(length=255), primary_key=False),
            Column(u'manager_s_email__c', MSString(length=255), primary_key=False),
            Column(u'want_preview__c', MSString(length=255), primary_key=False),
            Column(u'previewer_email__c', MSString(length=255), primary_key=False),
            Column(u'qa_case__c', MSString(length=255), primary_key=False),
            Column(u'internal_eb_tested__c', MSString(length=255), primary_key=False),
            Column(u'test_case_available__c', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sf_id_idx', sfcase.c.sf_id, unique=True)
Index(u'index_sfcase_on_contact_id', sfcase.c.contact_id, unique=False)
Index(u'index_sfcase_on_sf_id', sfcase.c.sf_id, unique=False)


sfcase_watcher =  Table('sfcase_watcher', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSBoolean(), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_activity_date', MSDate(), primary_key=False),
            Column(u'case_number_id__c', MSString(length=255), primary_key=False),
            Column(u'case_fields_deferred__c', MSString(length=255), primary_key=False),
            Column(u'tech_campaign_id__c', MSString(length=255), primary_key=False),
            Column(u'user_id__c', MSString(length=255), primary_key=False),
            Column(u'account_id__c', MSString(length=255), primary_key=False),
            Column(u'case_fields__c', MSString(length=255), primary_key=False),
            Column(u'case_scope__c', MSString(length=255), primary_key=False),
            Column(u'component_id__c', MSString(length=255), primary_key=False),
            Column(u'team_id__c', MSString(length=255), primary_key=False),
    
    
    )


sfcase_watcher_list =  Table('sfcase_watcher_list', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSBoolean(), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_activity_date', MSDate(), primary_key=False),
            Column(u'contact_id__c', MSString(length=255), primary_key=False),
            Column(u'alias_email__c', MSString(length=255), primary_key=False),
            Column(u'case_watcher_id__c', MSString(length=255), primary_key=False),
            Column(u'email__c', MSString(length=255), primary_key=False),
    
    
    )


sfcatdata =  Table('sfcatdata', metadata,
    Column(u'id', MSInteger(display_width=18), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'category_node_id', MSString(length=255), primary_key=False),
            Column(u's_object_id', MSString(length=255), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'related_sobject_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
    
    
    )
Index(u'Category Data ID', sfcatdata.c.sf_id, unique=False)
Index(u'sfcatdata_sf_id_idx', sfcatdata.c.sf_id, unique=True)
Index(u'Created By ID', sfcatdata.c.created_by_id, unique=False)
Index(u'Category Node ID', sfcatdata.c.category_node_id, unique=False)
Index(u'Last Modified By ID', sfcatdata.c.last_modified_by_id, unique=False)
Index(u'SObject ID', sfcatdata.c.s_object_id, unique=False)
Index(u'index_sfcatdata_on_category_node_id', sfcatdata.c.category_node_id, unique=False)
Index(u'index_sfcatdata_on_related_sobject_id', sfcatdata.c.related_sobject_id, unique=False)


sfcatnode =  Table('sfcatnode', metadata,
    Column(u'id', MSInteger(display_width=18), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'subcategory_sort_style', MSString(length=255), primary_key=False),
            Column(u'parent_category_node_id', MSString(length=255), primary_key=False),
            Column(u'sort_order', MSDouble(precision=None, scale=None, asdecimal=True), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'parent_id', MSString(length=255), primary_key=False),
            Column(u'master_label', MSString(length=255), primary_key=False),
            Column(u'sort_style', MSString(length=255), primary_key=False),
    
    
    )
Index(u'Category Node ID', sfcatnode.c.sf_id, unique=False)
Index(u'Last Modified By ID', sfcatnode.c.last_modified_by_id, unique=False)
Index(u'Created By ID', sfcatnode.c.created_by_id, unique=False)
Index(u'Parent Category Node ID', sfcatnode.c.parent_category_node_id, unique=False)
Index(u'index_sfcatnode_on_sf_id', sfcatnode.c.sf_id, unique=False)
Index(u'index_sfcatnode_on_parent_id', sfcatnode.c.parent_id, unique=False)
Index(u'sfcatnode_sf_id_idx', sfcatnode.c.sf_id, unique=True)


sfccomment =  Table('sfccomment', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'parent_id', MSString(length=255), primary_key=False),
            Column(u'is_published', MSString(length=255), primary_key=False),
            Column(u'comment_body', MSLongText(), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'last_modified_date', MSString(length=255), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfccomment_sf_id_idx', sfccomment.c.sf_id, unique=True)
Index(u'index_sfccomment_on_parent_id', sfccomment.c.parent_id, unique=False)


sfcomponent =  Table('sfcomponent', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSBoolean(), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'list_address__c', MSString(length=255), primary_key=False),
            Column(u'lookup__c', MSString(length=255), primary_key=False),
            Column(u'list_alias__c', MSString(length=255), primary_key=False),
            Column(u'description__c', MSString(length=255), primary_key=False),
            Column(u'product_team_id__c', MSString(length=255), primary_key=False),
            Column(u'pe_approver_id__c', MSString(length=255), primary_key=False),
            Column(u'business_unit__c', MSString(length=255), primary_key=False),
            Column(u'vp_id__c', MSString(length=255), primary_key=False),
    
    
    )


sfcontact =  Table('sfcontact', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'account_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'last_name', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'first_name', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'salutation', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'record_type_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_street', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_city', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_state', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_postal_code', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_country', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mailing_street', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mailing_city', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mailing_state', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mailing_postal_code', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mailing_country', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'phone', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'fax', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mobile_phone', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'home_phone', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'other_phone', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'assistant_phone', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'reports_to_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'email', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'title', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'department', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'assistant_name', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'lead_source', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'birthdate', MSDate(), primary_key=False),
            Column(u'description', MSLongText(charset=u'latin1'), primary_key=False),
            Column(u'owner_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'has_opted_out_of_email', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_cu_request_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_cu_update_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'portal_password__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'magma_user__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'contact_status__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'personal_invite_only__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'product_group__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'notification_frequency__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'mail_stop__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'contact_user_id__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'frequency__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'last_report__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'business_unit__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'notification_last_sent__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'dont_send_empty_report__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'list_alias__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'start_date__c', MSDate(), primary_key=False),
            Column(u'orientation_date__c', MSDate(), primary_key=False),
            Column(u'laptop__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'linux_workstation__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'sun_workstation__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'special_requests_admin__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'dept__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'special_requests_it__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'employee_number__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'users_without_emp_num__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'contacts_without_emp_num__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_last_login_date__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'portal_login_count__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_last_login_date_fmt__c', MSDate(), primary_key=False),
            Column(u'local_name__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_username__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'reassign_to_user_id__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'branches_approved_by_user_id__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'branches_approved_by__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'reassign_to__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'pr_cr_detail_level__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'pr_frequency__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'pr_last_report_date_time__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'pr_no_empty__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'pr_branch_detail_level__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'local_title__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'localized_dept__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'localized_business_unit__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_last_login_fail_date__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'portal_login_fail_count__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'tags__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_login_success__c', MSFloat(precision=None, scale=None, asdecimal=False), primary_key=False),
            Column(u'portal_total_login_seconds__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_max_login_seconds__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'portal_average_login_seconds__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'order_download_until__c', MSDate(), primary_key=False),
            Column(u'order_rtu_id__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'hr_survey__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'license_delivery_contact__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'full_name__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'last_login_failed__c', MSString(length=255, charset=u'latin1'), primary_key=False),
            Column(u'sf_id', MSString(length=255, charset=u'latin1'), primary_key=False, nullable=False),
            Column(u'portal_privilege__c', MSString(length=255), primary_key=False),
            Column(u'portal_last_confirm_date__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'portal_last_confirm_sent_date__c', MSDateTime(timezone=False), primary_key=False),
            Column(u'user_id__c', MSString(length=255), primary_key=False),
            Column(u'welcome_email_sent_at__c', MSString(length=255), primary_key=False),
            Column(u'password_reset_sent_at__c', MSString(length=255), primary_key=False),
            Column(u'portal_last_version__c', MSString(length=255), primary_key=False),
            Column(u'portal_server__c', MSString(length=255), primary_key=False),
            Column(u'email_flyer__c', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'last_activity_date', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
            Column(u'master_record_id', MSString(length=255), primary_key=False),
            Column(u'last_read_marketing_message_id', MSString(length=255), primary_key=False),
            Column(u'account_filter_ids_array', MSText(), primary_key=False),
            Column(u'marketing_message_read_count', MSInteger(display_width=11), primary_key=False),
            Column(u'total_score__c', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfcontact_sf_id_idx', sfcontact.c.sf_id, unique=True)
Index(u'index_sfcontact_on_sf_id', sfcontact.c.sf_id, unique=False)


sfcontact_setting =  Table('sfcontact_setting', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sfcontact_id', MSString(length=255), primary_key=False),
            Column(u'token', MSString(length=255), primary_key=False),
    
    
    )
Index(u'index_sfcontact_setting_on_sfcontact_id', sfcontact_setting.c.sfcontact_id, unique=False)


sfgroup =  Table('sfgroup', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'related_id', MSString(length=255), primary_key=False),
            Column(u'type', MSString(length=255), primary_key=False),
            Column(u'email', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'does_send_email_to_members', MSBoolean(), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'sf_type', MSString(length=255), primary_key=False),
    
    
    )


sfmolten_post =  Table('sfmolten_post', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'record_type_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'body__c', MSText(), primary_key=False),
            Column(u'page__c', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'valid_from__c', MSString(length=255), primary_key=False),
            Column(u'valid_to__c', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
            Column(u'title_long__c', MSString(length=255), primary_key=False),
    
    
    )


sfproduct_team =  Table('sfproduct_team', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSBoolean(), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'description__c', MSString(length=255), primary_key=False),
            Column(u'lookup__c', MSString(length=255), primary_key=False),
            Column(u'build_account__c', MSString(length=255), primary_key=False),
            Column(u'business_unit__c', MSString(length=255), primary_key=False),
            Column(u'products__c', MSString(length=255), primary_key=False),
            Column(u'bu_description__c', MSString(length=255), primary_key=False),
            Column(u'team_alias__c', MSString(length=255), primary_key=False),
            Column(u'build_account_contact_id__c', MSString(length=255), primary_key=False),
    
    
    )


sfsolution =  Table('sfsolution', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'solution_number', MSInteger(display_width=10), primary_key=False),
            Column(u'solution_name', MSString(length=255), primary_key=False),
            Column(u'is_published', MSString(length=255), primary_key=False),
            Column(u'is_published_in_public_kb', MSString(length=255), primary_key=False),
            Column(u'status', MSString(length=255), primary_key=False),
            Column(u'record_type_id', MSString(length=255), primary_key=False),
            Column(u'is_reviewed', MSString(length=255), primary_key=False),
            Column(u'solution_note', MSLongText(), primary_key=False),
            Column(u'owner_id', MSString(length=255), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'solution_type__c', MSString(length=255), primary_key=False),
            Column(u'account_specific__c', MSString(length=255), primary_key=False),
            Column(u'account_name__c', MSString(length=255), primary_key=False),
            Column(u'publish_request__c', MSString(length=255), primary_key=False),
            Column(u'initial_version__c', MSString(length=255), primary_key=False),
            Column(u'final_version__c', MSString(length=255), primary_key=False),
            Column(u'special_build__c', MSString(length=255), primary_key=False),
            Column(u'effective_date__c', MSDate(), primary_key=False),
            Column(u'product_name__c', MSString(length=255), primary_key=False),
            Column(u'component__c', MSString(length=255), primary_key=False),
            Column(u'sme_reviewer_id__c', MSString(length=255), primary_key=False),
            Column(u'sub_status__c', MSString(length=255), primary_key=False),
            Column(u'question_problem__c', MSString(length=255), primary_key=False),
            Column(u'answer_workaround__c', MSString(length=255), primary_key=False),
            Column(u'error_warning_message__c', MSString(length=255), primary_key=False),
            Column(u'message_description__c', MSString(length=255), primary_key=False),
            Column(u'solution_workaround__c', MSString(length=255), primary_key=False),
            Column(u'solution_answer__c', MSString(length=255), primary_key=False),
            Column(u'enter_solution_error_message__c', MSString(length=255), primary_key=False),
            Column(u'test_solution__c', MSString(length=255), primary_key=False),
            Column(u'test_error__c', MSString(length=255), primary_key=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'approve__c', MSString(length=255), primary_key=False),
            Column(u'reject__c', MSString(length=255), primary_key=False),
            Column(u'region__c', MSString(length=255), primary_key=False),
            Column(u'times_used', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'published_date__c', MSString(length=255), primary_key=False),
            Column(u'is_deleted', MSString(length=255), primary_key=False),
            Column(u'portal_account_name_id__c', MSString(length=255), primary_key=False),
            Column(u'publish_approved__c', MSString(length=255), primary_key=False),
            Column(u'is_html', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfsolution_sf_id_idx', sfsolution.c.sf_id, unique=True)
Index(u'index_sfsolution_on_sf_id', sfsolution.c.sf_id, unique=False)


sfsolution_setting =  Table('sfsolution_setting', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'sfsolution_id', MSString(length=255), primary_key=False),
            Column(u'views', MSInteger(display_width=11), primary_key=False),
            Column(u'relevancy', MSInteger(display_width=11), primary_key=False),
            Column(u'updates', MSInteger(display_width=11), primary_key=False),
    
    
    )


sfssl =  Table('sfssl', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'last_name', MSString(length=255), primary_key=False),
            Column(u'first_name', MSString(length=255), primary_key=False),
            Column(u'username', MSString(length=255), primary_key=False),
            Column(u'email', MSString(length=255), primary_key=False),
            Column(u'is_active', MSString(length=255), primary_key=False),
            Column(u'time_zone_sid_key', MSString(length=255), primary_key=False),
            Column(u'locale_sid_key', MSString(length=255), primary_key=False),
            Column(u'contact_id', MSString(length=255), primary_key=False),
            Column(u'language_locale_key', MSString(length=255), primary_key=False),
            Column(u'super_user', MSString(length=255), primary_key=False),
            Column(u'last_login_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'system_modstamp', MSString(length=255), primary_key=False),
            Column(u'name', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfssl_sf_id_idx', sfssl.c.sf_id, unique=True)


sfuser =  Table('sfuser', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'username', MSString(length=255), primary_key=False),
            Column(u'last_name', MSString(length=255), primary_key=False),
            Column(u'first_name', MSString(length=255), primary_key=False),
            Column(u'company_name', MSString(length=255), primary_key=False),
            Column(u'division', MSString(length=255), primary_key=False),
            Column(u'department', MSString(length=255), primary_key=False),
            Column(u'title', MSString(length=255), primary_key=False),
            Column(u'street', MSString(length=255), primary_key=False),
            Column(u'city', MSString(length=255), primary_key=False),
            Column(u'state', MSString(length=255), primary_key=False),
            Column(u'postal_code', MSString(length=255), primary_key=False),
            Column(u'country', MSString(length=255), primary_key=False),
            Column(u'email', MSString(length=255), primary_key=False),
            Column(u'phone', MSString(length=255), primary_key=False),
            Column(u'fax', MSString(length=255), primary_key=False),
            Column(u'mobile_phone', MSString(length=255), primary_key=False),
            Column(u'alias', MSString(length=255), primary_key=False),
            Column(u'is_active', MSString(length=255), primary_key=False),
            Column(u'time_zone_sid_key', MSString(length=255), primary_key=False),
            Column(u'user_role_id', MSString(length=255), primary_key=False),
            Column(u'locale_sid_key', MSString(length=255), primary_key=False),
            Column(u'receives_info_emails', MSString(length=255), primary_key=False),
            Column(u'receives_admin_info_emails', MSString(length=255), primary_key=False),
            Column(u'email_encoding_key', MSString(length=255), primary_key=False),
            Column(u'profile_id', MSString(length=255), primary_key=False),
            Column(u'language_locale_key', MSString(length=255), primary_key=False),
            Column(u'employee_number', MSString(length=255), primary_key=False),
            Column(u'last_login_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'created_by_id', MSString(length=255), primary_key=False),
            Column(u'last_modified_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'last_modified_by_id', MSString(length=255), primary_key=False),
            Column(u'system_modstamp', MSDateTime(timezone=False), primary_key=False),
            Column(u'offline_trial_expiration_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'offline_pda_trial_expiration_date', MSDateTime(timezone=False), primary_key=False),
            Column(u'user_permissions_marketing_user', MSString(length=255), primary_key=False),
            Column(u'user_permissions_offline_user', MSString(length=255), primary_key=False),
            Column(u'user_permissions_avantgo_user', MSString(length=255), primary_key=False),
            Column(u'forecast_enabled', MSString(length=255), primary_key=False),
            Column(u'reports_to__c', MSString(length=255), primary_key=False),
            Column(u'lookup_user__c', MSString(length=255), primary_key=False),
            Column(u'ex_employee__c', MSString(length=255), primary_key=False),
            Column(u'user_contact_id__c', MSString(length=255), primary_key=False, nullable=False),
            Column(u'description__c', MSString(length=255), primary_key=False, nullable=False),
            Column(u'sf_id', MSString(length=255), primary_key=False, nullable=False),
            Column(u'name', MSString(length=255), primary_key=False),
            Column(u'default_currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'currency_iso_code', MSString(length=255), primary_key=False),
            Column(u'next_automated_approver_id__c', MSString(length=255), primary_key=False),
            Column(u'expense_approving_manager_id__c', MSString(length=255), primary_key=False),
            Column(u'profile_license_type', MSString(length=255), primary_key=False),
            Column(u'delegated_approver_id', MSString(length=255), primary_key=False),
            Column(u'user_permissions_mobile_user', MSString(length=255), primary_key=False),
            Column(u'user_preferences_activity_reminders_popup', MSString(length=255), primary_key=False),
            Column(u'user_preferences_event_reminders_checkbox_default', MSString(length=255), primary_key=False),
            Column(u'user_preferences_task_reminders_checkbox_default', MSString(length=255), primary_key=False),
            Column(u'user_preferences_reminder_sound_off', MSString(length=255), primary_key=False),
            Column(u'extension', MSString(length=255), primary_key=False),
            Column(u'full_name__c', MSString(length=255), primary_key=False),
            Column(u'user_permissions_call_center_auto_login', MSString(length=255), primary_key=False),
            Column(u'call_center_id', MSString(length=255), primary_key=False),
            Column(u'contact_id', MSString(length=255), primary_key=False),
            Column(u'user_type', MSString(length=255), primary_key=False),
            Column(u'manager_id', MSString(length=255), primary_key=False),
            Column(u'unix_username__c', MSString(length=255), primary_key=False),
    
    
    )
Index(u'sfuser_sf_id_idx', sfuser.c.sf_id, unique=True)
Index(u'index_sfuser_on_sf_id', sfuser.c.sf_id, unique=False)


solution_relevancy =  Table('solution_relevancy', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'rating_value_one', MSInteger(display_width=11), primary_key=False),
            Column(u'rating_value_two', MSInteger(display_width=11), primary_key=False),
            Column(u'rating_value_three', MSInteger(display_width=11), primary_key=False),
            Column(u'rating_value_four', MSInteger(display_width=11), primary_key=False),
            Column(u'view_value', MSInteger(display_width=11), primary_key=False),
            Column(u'update_value', MSInteger(display_width=11), primary_key=False),
    
    
    )


solution_search_log =  Table('solution_search_log', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'contact_id', MSInteger(display_width=11), primary_key=False),
            Column(u'term', MSString(length=255), primary_key=False),
            Column(u'results_count', MSInteger(display_width=11), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )


tip =  Table('tip', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'title', MSString(length=255), primary_key=False),
            Column(u'body', MSText(), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'updated_at', MSDateTime(timezone=False), primary_key=False),
            Column(u'page_id', MSInteger(display_width=11), primary_key=False),
    
    
    )


viewing =  Table('viewing', metadata,
    Column(u'id', MSInteger(display_width=11), primary_key=True, nullable=False),
            Column(u'viewable_id', MSString(length=255), primary_key=False),
            Column(u'viewable_type', MSString(length=255), primary_key=False),
            Column(u'sfcontact_id', MSString(length=255), primary_key=False),
            Column(u'created_at', MSDateTime(timezone=False), primary_key=False),
    
    
    )
Index(u'index_viewing_on_sfcontact_id', viewing.c.sfcontact_id, unique=False)
Index(u'index_viewing_on_viewable_type', viewing.c.viewable_type, unique=False)

