#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

script_16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABPRJ"
    "REFUWIWtl02PFEUYx39V1a/Tw84Mwy4JISEQUM4E9aImrFfxqN5IFP0E6tlvo6An9aBeBGRx"
    "deEKWUK44CaEsDu7M9M73dXVXR6mu933mV14kkq6O1X1/J//89pCSMWryI8/3LSXL1+m3++z"
    "ublJnucopTh27Bi9Xo9333tfHHTeeSXtQLvdJssyfN/HcRzyPMdaS1EUOM7k68VhGfj9t1/t"
    "uXPn6PV6teIwDImiqAagtSaOY7IsI4oihsMhb739zp5MHJqBRqMBjC0XQtRWGmPQOkMpSb/f"
    "Z3FxkeXlZcIwRGu9730TGbhz+5admZnh5cuXCCFoNBrMzMzQarVoNBo4jkOapqyurpEkCY1G"
    "yMrKClfmPzjQ95VMZGCrMmstUsqadsdxkFIihEApiVIKIQRFUUyje28A//y9aK21rK+vEwRB"
    "/b3b7eK6LgBCCKSUWGux1o4vchxct0BKObXyPQEEQYjneTSbzfJSlzAcf6uUAthyfxUHYRgi"
    "pURrjed5UwOoY+DG99/ZMdURrdYM7XabIAjwfR+lFEopiqIYp1mpWJX0A1hrGY1GrK6u0u/3"
    "yfOcZ8+e8fEnn05XB2Zn5/A8F2tBSoXruriuW/u4KC0XQozXlueKds/ziKIIKSVSyqnqQO2w"
    "caoIfN/H8zyUGjOT53m9gJqNKuC2WeM4tFotjh8/XoNZ/OuevXnje8s+UkN0XRff94miiCAI"
    "UMpBSFlbSrm2WrxTKmCVQb7vMzc3twvoNgC3b/1hxwcdGo0GrVYLz/Nw3HGKyVIpJe3TiBAC"
    "13XJ85wsyzDG7LtXPn/+nDiOa5+5rlvnd7WUUqgt79MAcByn7g++Hxywt8yCewsLttvt0mq1"
    "8H0ft2QAOHRuF0VBURQYY0iShMFgyMrKvzx58oTrX3y5jcg6BpaWlrh48U0uXHgDKQVSiiMp"
    "r87szIyzZ8/Sbrd37d3VCx7cX7LdbpcwDEsm3DqwDitV3TDGMBqNGAwGPH78mOXlZb76+hsB"
    "e1RCrTXGGLIsw3GcqXJ5P6mYEEKQ5zlRFHH+/HlmZ2frPbturypf5cfXIVUDqwwKgoBffv7J"
    "Pnz4ECXEdh/Pz1/5tjqwtdhUVe8oMu6W/xewCkS3291/Hnhwf8l2Oh2UUoRhSBiGdTc8qlhr"
    "SdOUNE3p9Xr0er3954FHjx5x5swZOp0OQN0Jt1a7SVK5sO6g1tbxVc2OEyeiewt37YkTJ2om"
    "oijC9/2pAeR5XsdTnuekaUqSJKyvb7C+sT55Inr69ClFURBFEdbaukNWFfIgi6tiVFmdZVnt"
    "Aq01eV5MPxUv3P3Tnjx5EiklQRDsycRWayuLdWbItGYYx8RxjDEZuTEIIZFKTj8Vr6ysEAQB"
    "juNQFMW4Ye2oETstNsagM0OapvT7Awb9DYbxkM14k2YzotlsHv6/4M7tW/b06dMEQbANRJ4X"
    "GFMq1ZokSUqqMzJjEEKQJglX5uf37gXTynA4RClV+jDH8zyEEGidobUmyzK0HgdaHMcMhzFJ"
    "ktA81sTuUdgODaBSOBqNsNbi+z7WWuLNEUmSlOlV4LouRVHw4dWrr/ffsCpGaZpijKmDbWMw"
    "II430VojhaDTaZMkycT7pgZw/fPP7KVLl3Ach42NDUzp1wpUp90mGSV8NMHiIwO4du0ap06d"
    "Ym1tjcFgUE5PY3f4vk8Qhrx48eIwugH4D0QiX21BDvpuAAAAAElFTkSuQmCC")
getscript_16x16Data = script_16x16.GetData
getscript_16x16Image = script_16x16.GetImage
getscript_16x16Bitmap = script_16x16.GetBitmap

